Repository OMZigak/KKUYOS, pull requests merged in 2024-07, with the labels that each got.

#90 [setting] 프로젝트 세팅
  KkuMulKum.xcodeproj/project.pbxproj
  KkuMulKum/AppDelegate.swift
  KkuMulKum/Application/AppDelegate.swift
  KkuMulKum/Application/SceneDelegate.swift
  KkuMulKum/Resource/Assets.xcassets/AccentColor.colorset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/AppIcon.appiconset/appstore.png
  KkuMulKum/Resource/Assets.xcassets/Contents.json
  KkuMulKum/Resource/Base.lproj/LaunchScreen.storyboard
  KkuMulKum/Resource/Color.xcassets/Contents.json
  KkuMulKum/Resource/Color.xcassets/gray1.colorset/Contents.json
  KkuMulKum/Resource/Color.xcassets/gray2.colorset/Contents.json
  KkuMulKum/Resource/Color.xcassets/gray3.colorset/Contents.json
  KkuMulKum/Resource/Color.xcassets/gray4.colorset/Contents.json
  KkuMulKum/Resource/Color.xcassets/gray5.colorset/Contents.json
  KkuMulKum/Resource/Color.xcassets/gray6.colorset/Contents.json
  KkuMulKum/Resource/Color.xcassets/gray7.colorset/Contents.json
  KkuMulKum/Resource/Color.xcassets/gray8.colorset/Contents.json
  KkuMulKum/Resource/Color.xcassets/gray9.colorset/Contents.json
  KkuMulKum/Resource/Color.xcassets/green1.colorset/Contents.json
  KkuMulKum/Resource/Color.xcassets/green2.colorset/Contents.json
  KkuMulKum/Resource/Color.xcassets/green3.colorset/Contents.json
  KkuMulKum/Resource/Color.xcassets/green4.colorset/Contents.json
  KkuMulKum/Resource/Color.xcassets/green5.colorset/Contents.json
  KkuMulKum/Resource/Color.xcassets/green6.colorset/Contents.json
  KkuMulKum/Resource/Color.xcassets/lightGreen.colorset/Contents.json
  KkuMulKum/Resource/Color.xcassets/maincolor.colorset/Contents.json
  KkuMulKum/Resource/Color.xcassets/orange1.colorset/Contents.json
  KkuMulKum/Resource/Color.xcassets/orange2.colorset/Contents.json
  KkuMulKum/Resource/Color.xcassets/orange3.colorset/Contents.json
  KkuMulKum/Resource/Extension/NSAttributedString+.swift
  KkuMulKum/Resource/Extension/UIButton+.swift
  KkuMulKum/Resource/Extension/UIFont+.swift
  KkuMulKum/Resource/Extension/UILabel+.swift
  KkuMulKum/Resource/Extension/UIStackView+.swift
  KkuMulKum/Resource/Extension/UITextField+.swift
  KkuMulKum/Resource/Extension/UIView+.swift
  KkuMulKum/Resource/Font/Pretendard-Black.otf
  KkuMulKum/Resource/Font/Pretendard-Bold.otf
  KkuMulKum/Resource/Font/Pretendard-ExtraBold.otf
  KkuMulKum/Resource/Font/Pretendard-ExtraLight.otf
  KkuMulKum/Resource/Font/Pretendard-Light.otf
  KkuMulKum/Resource/Font/Pretendard-Medium.otf
  KkuMulKum/Resource/Font/Pretendard-Regular.otf
  KkuMulKum/Resource/Font/Pretendard-SemiBold.otf
  KkuMulKum/Resource/Font/Pretendard-Thin.otf
  KkuMulKum/Resource/Info.plist
  KkuMulKum/Resource/Util/ReuseIdentifiable.swift
  KkuMulKum/Resource/Util/Screen.swift
  KkuMulKum/SceneDelegate.swift
  KkuMulKum/Source/ViewController.swift
Labels: ⚙️ setting, 🧀 add, 💙 JinUng

#115 [add] Base 클래스 추가
  KkuMulKum.xcodeproj/project.pbxproj
  KkuMulKum/Resource/Base/BaseCollectionReusableView.swift
  KkuMulKum/Resource/Base/BaseCollectionViewCell.swift
  KkuMulKum/Resource/Base/BaseTableViewCell.swift
  KkuMulKum/Resource/Base/BaseView.swift
  KkuMulKum/Resource/Base/BaseViewController.swift
Labels: 🧀 add, 💙 JinUng

#120 [add] ObservablePattern, MoyaLoggingPlugin 추가
  KkuMulKum.xcodeproj/project.pbxproj
  KkuMulKum/Network/MoyaLoggingPlugin.swift
  KkuMulKum/Resource/ObservablePattern/ObservablePattern.swift
Labels: 🧀 add, 💙 JinUng

#122 [add] 에셋 추가
  KkuMulKum/Resource/Assets.xcassets/icon_back.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/icon_back.imageset/back.svg
  KkuMulKum/Resource/Assets.xcassets/icon_camera.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/icon_camera.imageset/camera.svg
  KkuMulKum/Resource/Assets.xcassets/icon_check.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/icon_check.imageset/check.svg
  KkuMulKum/Resource/Assets.xcassets/icon_date.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/icon_date.imageset/date.svg
  KkuMulKum/Resource/Assets.xcassets/icon_delete.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/icon_delete.imageset/delete.svg
  KkuMulKum/Resource/Assets.xcassets/icon_deleteDark.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/icon_deleteDark.imageset/deleteDark.svg
  KkuMulKum/Resource/Assets.xcassets/icon_group.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/icon_group.imageset/group.svg
  KkuMulKum/Resource/Assets.xcassets/icon_groupPlus.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/icon_groupPlus.imageset/groupPlus.svg
  KkuMulKum/Resource/Assets.xcassets/icon_home.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/icon_home.imageset/home.svg
  KkuMulKum/Resource/Assets.xcassets/icon_my.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/icon_my.imageset/my.svg
  KkuMulKum/Resource/Assets.xcassets/icon_penalty.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/icon_penalty.imageset/penalty.svg
  KkuMulKum/Resource/Assets.xcassets/icon_pin.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/icon_pin.imageset/pin.svg
  KkuMulKum/Resource/Assets.xcassets/icon_plus.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/icon_plus.imageset/plus.svg
  KkuMulKum/Resource/Assets.xcassets/icon_plusDark.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/icon_plusDark.imageset/plusDark.svg
  KkuMulKum/Resource/Assets.xcassets/icon_right.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/icon_right.imageset/right.svg
  KkuMulKum/Resource/Assets.xcassets/icon_search.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/icon_search.imageset/search.svg
  KkuMulKum/Resource/Assets.xcassets/icon_time.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/icon_time.imageset/time.svg
  KkuMulKum/Resource/Assets.xcassets/img_logo.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/img_logo.imageset/logo.png
  KkuMulKum/Resource/Assets.xcassets/img_logo.imageset/logo@2x.png
  KkuMulKum/Resource/Assets.xcassets/img_logo.imageset/logo@3x.png
  KkuMulKum/Resource/Assets.xcassets/img_profile.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/img_profile.imageset/profileBasic.png
  KkuMulKum/Resource/Assets.xcassets/img_profile.imageset/profileBasic@2x.png
  KkuMulKum/Resource/Assets.xcassets/img_profile.imageset/profileBasic@3x.png
Labels: 🧀 add, ❤️ SuYeon

#124 [feat] 기본 탭바 구현
  KkuMulKum.xcodeproj/project.pbxproj
  KkuMulKum/Application/SceneDelegate.swift
  KkuMulKum/Resource/Assets.xcassets/Image/Contents.json
  KkuMulKum/Resource/Assets.xcassets/Image/img_logo.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/Image/img_logo.imageset/logo.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_logo.imageset/logo@2x.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_logo.imageset/logo@3x.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_profile.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/Image/img_profile.imageset/profileBasic.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_profile.imageset/profileBasic@2x.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_profile.imageset/profileBasic@3x.png
  KkuMulKum/Resource/Assets.xcassets/icon_back.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/icon_back.imageset/back.svg
  KkuMulKum/Resource/Assets.xcassets/icon_camera.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/icon_camera.imageset/camera.svg
  KkuMulKum/Resource/Assets.xcassets/icon_check.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/icon_check.imageset/check.svg
  KkuMulKum/Resource/Assets.xcassets/icon_date.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/icon_date.imageset/date.svg
  KkuMulKum/Resource/Assets.xcassets/icon_delete.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/icon_delete.imageset/delete.svg
  KkuMulKum/Resource/Assets.xcassets/icon_deleteDark.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/icon_deleteDark.imageset/deleteDark.svg
  KkuMulKum/Resource/Assets.xcassets/icon_group.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/icon_group.imageset/group.svg
  KkuMulKum/Resource/Assets.xcassets/icon_groupPlus.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/icon_groupPlus.imageset/groupPlus.svg
  KkuMulKum/Resource/Assets.xcassets/icon_home.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/icon_home.imageset/home.svg
  KkuMulKum/Resource/Assets.xcassets/icon_my.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/icon_my.imageset/my.svg
  KkuMulKum/Resource/Assets.xcassets/icon_penalty.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/icon_penalty.imageset/penalty.svg
  KkuMulKum/Resource/Assets.xcassets/icon_pin.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/icon_pin.imageset/pin.svg
  KkuMulKum/Resource/Assets.xcassets/icon_plus.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/icon_plus.imageset/plus.svg
  KkuMulKum/Resource/Assets.xcassets/icon_plusDark.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/icon_plusDark.imageset/plusDark.svg
  KkuMulKum/Resource/Assets.xcassets/icon_right.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/icon_right.imageset/right.svg
  KkuMulKum/Resource/Assets.xcassets/icon_search.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/icon_search.imageset/search.svg
  KkuMulKum/Resource/Assets.xcassets/icon_time.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/icon_time.imageset/time.svg
  KkuMulKum/Source/Core/MainTabBarController.swift
  KkuMulKum/Source/GroupList/GroupListViewController.swift
  KkuMulKum/Source/Home/HomeViewController.swift
  KkuMulKum/Source/MyPage/MyPageViewController.swift
  KkuMulKum/Source/ViewController.swift
Labels: ✨ feat, 💚 YouJin

#125 [setting] 스타일 가이드 수정사항 반영
  KkuMulKum/Resource/Color.xcassets/gray1.colorset/Contents.json
  KkuMulKum/Resource/Color.xcassets/gray2.colorset/Contents.json
  KkuMulKum/Resource/Color.xcassets/gray3.colorset/Contents.json
  KkuMulKum/Resource/Color.xcassets/gray4.colorset/Contents.json
  KkuMulKum/Resource/Color.xcassets/gray5.colorset/Contents.json
  KkuMulKum/Resource/Color.xcassets/gray6.colorset/Contents.json
  KkuMulKum/Resource/Color.xcassets/gray7.colorset/Contents.json
  KkuMulKum/Resource/Color.xcassets/gray8.colorset/Contents.json
  KkuMulKum/Resource/Color.xcassets/gray9.colorset/Contents.json
  KkuMulKum/Resource/Color.xcassets/green1.colorset/Contents.json
  KkuMulKum/Resource/Color.xcassets/green2.colorset/Contents.json
  KkuMulKum/Resource/Color.xcassets/green3.colorset/Contents.json
  KkuMulKum/Resource/Color.xcassets/green4.colorset/Contents.json
  KkuMulKum/Resource/Color.xcassets/lightGreen.colorset/Contents.json
  KkuMulKum/Resource/Color.xcassets/maincolor.colorset/Contents.json
  KkuMulKum/Resource/Color.xcassets/orange.colorset/Contents.json
  KkuMulKum/Resource/Color.xcassets/orange1.colorset/Contents.json
  KkuMulKum/Resource/Color.xcassets/orange2.colorset/Contents.json
  KkuMulKum/Resource/Color.xcassets/orange3.colorset/Contents.json
  KkuMulKum/Resource/Color.xcassets/red.colorset/Contents.json
  KkuMulKum/Resource/Extension/UIFont+.swift
  KkuMulKum/Resource/Extension/UILabel+.swift
Labels: ⚙️ setting, ❤️ SuYeon

#117 add: provisioning 등록
  KkuMulKum.xcodeproj/project.pbxproj
  KkuMulKum/KkuMulKum.entitlements
Labels: 🧀 add

#131 [add] 공통 컴포넌트 구현하기
  KkuMulKum.xcodeproj/project.pbxproj
  KkuMulKum/Resource/Components/CustomButton.swift
  KkuMulKum/Resource/Components/CustomTextField.swift
  KkuMulKum/Resource/Extension/UITextField+.swift
Labels: 🧀 add, 💙 JinUng

#132 [Feat] 카카오로그인구현
  KkuMulKum.xcodeproj/project.pbxproj
  KkuMulKum/Application/AppDelegate.swift
  KkuMulKum/Application/SceneDelegate.swift
  KkuMulKum/Source/Onboarding/Login/AppleLoginVC.swift
  KkuMulKum/Source/Onboarding/Login/KakaoLoginVC.swift
  KkuMulKum/Source/onBoarding/LoginVC.swift
Labels: ✨ feat, 🛠️ fix, 🧡 JiHoon

#141 [feat] Auth네트워크 Request, Response Model 구현
  KkuMulKum/Network/DTO/Model/Auth/AuthTemp.swift
  KkuMulKum/Network/DTO/Model/Auth/ResissueResponseModel.swift
  KkuMulKum/Network/DTO/Model/Auth/SocialLoginRequestModel.swift
  KkuMulKum/Network/DTO/Model/Auth/SocialLoginResponceModle.swift
Labels: ✨ feat, 🧡 JiHoon

#142 [feat] Promise 네트워크 Request, Response Model 구현
  KkuMulKum.xcodeproj/project.pbxproj
  KkuMulKum/Network/DTO/Model/Promises/AddPromiseRequestModel.swift
  KkuMulKum/Network/DTO/Model/Promises/ArrivalCompletionResponseModel.swift
  KkuMulKum/Network/DTO/Model/Promises/MyPromiseReadyInfoRequestModel.swift
  KkuMulKum/Network/DTO/Model/Promises/MyReadyStatusResponseModel.swift
  KkuMulKum/Network/DTO/Model/Promises/NearestPromiseResponseModel.swift
  KkuMulKum/Network/DTO/Model/Promises/PromiseInfoResponseModel.swift
  KkuMulKum/Network/DTO/Model/Promises/PromiseLateInfoResponseModel.swift
  KkuMulKum/Network/DTO/Model/Promises/PromiseParticipantListResponseModel.swift
  KkuMulKum/Network/DTO/Model/Promises/PromisesTemp.swift
  KkuMulKum/Network/DTO/Model/Promises/UpcomingPromiseListResponseModel.swift
Labels: ✨ feat, 💚 YouJin

#144 [refactor] ModelType 프로토콜 선언 및 실제 모델들 재정의
  KkuMulKum.xcodeproj/project.pbxproj
  KkuMulKum/Network/DTO/Model/Auth/ResissueResponseModel.swift
  KkuMulKum/Network/DTO/Model/Auth/SocialLoginRequestModel.swift
  KkuMulKum/Network/DTO/Model/Auth/SocialLoginResponseModel.swift
  KkuMulKum/Network/DTO/Model/Empty/EmptyModel.swift
  KkuMulKum/Network/DTO/Model/Meetings/MakeMeetingsRequestModel.swift
  KkuMulKum/Network/DTO/Model/Meetings/MakeMeetingsResponseModel.swift
  KkuMulKum/Network/DTO/Model/Meetings/MeetingInfoResponseModel.swift
  KkuMulKum/Network/DTO/Model/Meetings/MeetingListResponseModel.swift
  KkuMulKum/Network/DTO/Model/Meetings/MeetingMembersResponseModel.swift
  KkuMulKum/Network/DTO/Model/Meetings/RegisterMeetingsResponseModel.swift
  KkuMulKum/Network/DTO/Model/Promises/AddPromiseRequestModel.swift
  KkuMulKum/Network/DTO/Model/Promises/ArrivalCompletionResponseModel.swift
  KkuMulKum/Network/DTO/Model/Promises/MyPromiseReadyInfoRequestModel.swift
  KkuMulKum/Network/DTO/Model/Promises/MyReadyStatusResponseModel.swift
  KkuMulKum/Network/DTO/Model/Promises/NearestPromiseResponseModel.swift
  KkuMulKum/Network/DTO/Model/Promises/PromiseInfoResponseModel.swift
  KkuMulKum/Network/DTO/Model/Promises/PromiseLateInfoResponseModel.swift
  KkuMulKum/Network/DTO/Model/Promises/PromiseParticipantListResponseModel.swift
  KkuMulKum/Network/DTO/Model/Promises/UpcomingPromiseListResponseModel.swift
  KkuMulKum/Network/DTO/Model/Protocol/ModelType.swift
  KkuMulKum/Network/DTO/Model/Users/LoginUserResponseModel.swift
  KkuMulKum/Network/DTO/Model/Users/UpdateProfileNameModel.swift
  KkuMulKum/Network/DTO/ResponseBody/ResponseBodyDTO.swift
  KkuMulKum/Resource/Component/CustomButton.swift
  KkuMulKum/Resource/Component/CustomTextField.swift
  KkuMulKum/Resource/ViewController.swift
Labels: ♻️ refactor, 💙 JinUng

#147 [Feat] 로그인 페이지 구현
  File.swift
  KkuMulKum.xcodeproj/project.pbxproj
  KkuMulKum/Application/SceneDelegate.swift
  KkuMulKum/Resource/Assets.xcassets/login/Contents.json
  KkuMulKum/Resource/Assets.xcassets/login/appleLogin.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/login/appleLogin.imageset/login_btn_ios.png
  KkuMulKum/Resource/Assets.xcassets/login/kakaoLogin.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/login/kakaoLogin.imageset/login_btn_ios 1.png
  KkuMulKum/Resource/Assets.xcassets/login/kakaoLogin.imageset/login_btn_ios 2.png
  KkuMulKum/Resource/Assets.xcassets/login/kakaoLogin.imageset/login_btn_ios.png
  KkuMulKum/Resource/Info.plist
  KkuMulKum/Source/Onboarding/Login/AppleLoginVC.swift
  KkuMulKum/Source/Onboarding/Login/KakaoLoginVC.swift
  KkuMulKum/Source/Onboarding/Login/VIewModel/LoginViewModel.swift
  KkuMulKum/Source/Onboarding/Login/View/LoginView.swift
  KkuMulKum/Source/Onboarding/Login/ViewController/LoginViewController.swift
Labels: ✨ feat, 🧀 add, 🧡 JiHoon

#151 [hotfix] 라이브러리 추가 설치 및 경고 해결
  KkuMulKum.xcodeproj/project.pbxproj
  KkuMulKum.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  KkuMulKum/Resource/Protocol/ViewModelType.swift
  KkuMulKum/Source/Onboarding/Login/VIewModel/LoginViewModel.swift
Labels: 🛠️ fix, ⚙️ setting, 💚 YouJin

#152 [feat] 약속 상세 화면 중간 PR 및 NavigationBar 두개 겹치는 문제 해결, mainTabBar 색상 변경
  KkuMulKum.xcodeproj/project.pbxproj
  KkuMulKum/Application/AppDelegate.swift
  KkuMulKum/Application/SceneDelegate.swift
  KkuMulKum/Source/Core/MainTabBarController.swift
  KkuMulKum/Source/GroupList/GroupListViewController.swift
  KkuMulKum/Source/Promise/PromiseInfoViewController.swift
  KkuMulKum/Source/Promise/PromiseSegmentedControl.swift
  KkuMulKum/Source/Promise/PromiseViewController.swift
  KkuMulKum/Source/Promise/PromiseViewModel.swift
  KkuMulKum/Source/Promise/ReadyStatusViewController.swift
  KkuMulKum/Source/Promise/TardyViewController.swift
Labels: ✨ feat, 🛠️ fix, 💚 YouJin

#153 [feat] 마이페이지 UI 구현
  File.swift
  KkuMulKum.xcodeproj/project.pbxproj
  KkuMulKum/Resource/Assets.xcassets/Image/img_edit.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/Image/img_edit.imageset/edit.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_profile.imageset/my_btn_edit.png
  KkuMulKum/Source/MyPage/MyPageViewController.swift
  KkuMulKum/Source/MyPage/View/MyPageAlarmSettingView.swift
  KkuMulKum/Source/MyPage/View/MyPageContentView.swift
  KkuMulKum/Source/MyPage/View/MyPageEtcSettingView.swift
  KkuMulKum/Source/MyPage/View/MyPageNavigationView.swift
  KkuMulKum/Source/MyPage/ViewController/MyPageViewController.swift
Labels: ✨ feat, 🧡 JiHoon

#156 [feat] 온보딩 프로세스 구현완료
  KkuMulKum.xcodeproj/project.pbxproj
  KkuMulKum/Application/AppDelegate.swift
  KkuMulKum/Application/SceneDelegate.swift
  KkuMulKum/Resource/Assets.xcassets/Image/img_profile.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/Image/img_profile.imageset/Mask group.svg
  KkuMulKum/Resource/Assets.xcassets/Image/img_profile.imageset/ic_profilebasic.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_profile.imageset/ic_profilebasic@2x.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_profile.imageset/ic_profilebasic@3x.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_profile.imageset/my_btn_edit.png
  KkuMulKum/Resource/Assets.xcassets/Splash.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/Splash.imageset/Splash 1.png
  KkuMulKum/Resource/Assets.xcassets/Splash.imageset/Splash 2.png
  KkuMulKum/Resource/Assets.xcassets/Splash.imageset/Splash.png
  KkuMulKum/Resource/Base.lproj/LaunchScreen.storyboard
  KkuMulKum/Resource/Info.plist
  KkuMulKum/Source/MyPage/View/MyPageContentView.swift
  KkuMulKum/Source/Onboarding/Login/VIewModel/LoginViewModel.swift
  KkuMulKum/Source/Onboarding/Nickname/NicknameView/NicknameView.swift
  KkuMulKum/Source/Onboarding/Nickname/ViewController/NicknameViewController.swift
  KkuMulKum/Source/Onboarding/Nickname/ViewModel/NicknameViewModel.swift
  KkuMulKum/Source/Onboarding/Profile/VIewController/ProfileViewController.swift
  KkuMulKum/Source/Onboarding/Profile/View/ProfileView.swift
  KkuMulKum/Source/Onboarding/Profile/ViewModel/ProfileViewModel.swift
  KkuMulKum/Source/Onboarding/Welcome/View/WelcomeView.swift
  KkuMulKum/Source/Onboarding/Welcome/ViewController/WelcomeViewController.swift
  KkuMulKum/Source/Onboarding/Welcome/ViewModel/WelcomeViewModel.swift
Labels: ✨ feat, 🛠️ fix, 🧡 JiHoon

#158 [feat] 모임 상세 UI 구현
  KkuMulKum.xcodeproj/project.pbxproj
  KkuMulKum.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  KkuMulKum/Network/DTO/Model/Promises/MeetingPromisesModel.swift
  KkuMulKum/Resource/Assets.xcassets/Image/img_meetingInfoBanner.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/Image/img_meetingInfoBanner.imageset/meetingInfoBanner.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_meetingInfoBanner.imageset/meetingInfoBanner@2x.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_meetingInfoBanner.imageset/meetingInfoBanner@3x.png
  KkuMulKum/Resource/Extension/UIFont+.swift
  KkuMulKum/Resource/Util/Toast.swift
  KkuMulKum/Source/MeetingInfo/Service/MeetingInfoService.swift
  KkuMulKum/Source/MeetingInfo/View/InvitationCodePopUpView.swift
  KkuMulKum/Source/MeetingInfo/View/MeetingInfoBannerView.swift
  KkuMulKum/Source/MeetingInfo/View/MeetingInfoView.swift
  KkuMulKum/Source/MeetingInfo/View/MeetingMemberCell.swift
  KkuMulKum/Source/MeetingInfo/View/MeetingPromiseCell.swift
  KkuMulKum/Source/MeetingInfo/ViewController/InvitationCodePopUpViewController.swift
  KkuMulKum/Source/MeetingInfo/ViewController/MeetingInfoViewController.swift
  KkuMulKum/Source/MeetingInfo/ViewModel/MeetingInfoViewModel.swift
Labels: ✨ feat, 💙 JinUng

#163 [Refactor] 코드 컨벤션 반영
  KkuMulKum.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  KkuMulKum/Application/AppDelegate.swift
  KkuMulKum/Application/SceneDelegate.swift
  KkuMulKum/Resource/Assets.xcassets/Image/img_login.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/Image/img_login.imageset/img_login 1.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_login.imageset/img_login 2.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_login.imageset/img_login.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_welcome.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/Image/img_welcome.imageset/welcomeImg.svg
  KkuMulKum/Resource/Assets.xcassets/Splash.imageset/Splash 1.png
  KkuMulKum/Resource/Assets.xcassets/Splash.imageset/Splash 2.png
  KkuMulKum/Resource/Assets.xcassets/Splash.imageset/Splash.png
  KkuMulKum/Resource/Assets.xcassets/img_splash.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/img_splash.imageset/img_splash.svg
  KkuMulKum/Resource/Base.lproj/LaunchScreen.storyboard
  KkuMulKum/Resource/Base/BaseViewController.swift
  KkuMulKum/Source/Onboarding/Login/View/LoginView.swift
  KkuMulKum/Source/Onboarding/Login/ViewController/LoginViewController.swift
  KkuMulKum/Source/Onboarding/Nickname/NicknameView/NicknameView.swift
  KkuMulKum/Source/Onboarding/Profile/View/ProfileView.swift
  KkuMulKum/Source/Onboarding/Welcome/View/WelcomeView.swift
  KkuMulKum/Source/Onboarding/Welcome/ViewController/WelcomeViewController.swift
Labels: ✨ feat, 🛠️ fix, 🧡 JiHoon

#164 [feat] 모임 추가 뷰 구현
  KkuMulKum.xcodeproj/project.pbxproj
  KkuMulKum/Resource/Assets.xcassets/Image/img_create_group.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/Image/img_create_group.imageset/img_create_group.svg
  KkuMulKum/Resource/Base/BaseViewController.swift
  KkuMulKum/Source/GroupCreate/CheckInviteCode/View/CheckInviteCodeView.swift
  KkuMulKum/Source/GroupCreate/CheckInviteCode/View/JoinButtonView.swift
  KkuMulKum/Source/GroupCreate/CheckInviteCode/ViewController/CheckInviteCodeViewController.swift
  KkuMulKum/Source/GroupCreate/CreateGroup/Service/CreateGroupService.swift
  KkuMulKum/Source/GroupCreate/CreateGroup/View/CreateGroupView.swift
  KkuMulKum/Source/GroupCreate/CreateGroup/ViewController/CreateGroupViewController.swift
  KkuMulKum/Source/GroupCreate/CreateGroup/ViewModel/CreateGroupViewModel.swift
  KkuMulKum/Source/GroupCreate/FinishCreate/View/FinishCreateNavigationView.swift
  KkuMulKum/Source/GroupCreate/FinishCreate/ViewController/FinishCreateViewController.swift
  KkuMulKum/Source/GroupCreate/InviteCode/Service/InviteCodeService.swift
  KkuMulKum/Source/GroupCreate/InviteCode/View/InviteCodeView.swift
  KkuMulKum/Source/GroupCreate/InviteCode/ViewController/InviteCodeViewController.swift
  KkuMulKum/Source/GroupCreate/InviteCode/ViewModel/InviteCodeViewModel.swift
  KkuMulKum/Source/GroupList/GroupListViewController.swift
  KkuMulKum/Source/MeetingInfo/ViewController/MeetingInfoViewController.swift
Labels: ✨ feat, 💚 YouJin

#165 [feat] 내 모임 리스트 UI 구현
  KkuMulKum.xcodeproj/project.pbxproj
  KkuMulKum.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  KkuMulKum/Resource/Assets.xcassets/Icon/ic_groupPlus.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/Icon/ic_groupPlus.imageset/ic_grpplus.svg
  KkuMulKum/Resource/Assets.xcassets/Icon/icon_groupPlus.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/Icon/icon_groupPlus.imageset/groupPlus.svg
  KkuMulKum/Source/Core/MainTabBarController.swift
  KkuMulKum/Source/GroupCreate/CreateGroup/ViewController/CreateGroupViewController.swift
  KkuMulKum/Source/GroupCreate/InviteCode/ViewController/InviteCodeViewController.swift
  KkuMulKum/Source/MeetingList/Cell/MeetingTableViewCell.swift
  KkuMulKum/Source/MeetingList/Model/MeetingDummyModel.swift
  KkuMulKum/Source/MeetingList/View/MeetingListView.swift
  KkuMulKum/Source/MeetingList/ViewController/MeetingListViewController.swift
  KkuMulKum/Source/MeetingList/ViewModel/MeetingListViewModel.swift
Labels: ✨ feat, ❤️ SuYeon

#161 [feat] 홈 UI 구현
  KkuMulKum.xcodeproj/project.pbxproj
  KkuMulKum.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  KkuMulKum/Resource/Assets.xcassets/Image/img_board.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/Image/img_board.imageset/Group 427320589.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_board.imageset/Group 427320589@2x.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_board.imageset/Group 427320589@3x.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_emptyCharacter.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/Image/img_emptyCharacter.imageset/Frame 1171276907.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_emptyCharacter.imageset/Frame 1171276907@2x.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_emptyCharacter.imageset/Frame 1171276907@3x.png
  KkuMulKum/Source/Core/MainTabBarController.swift
  KkuMulKum/Source/Home/Cell/UpcomingPromiseCollecitonViewCell.swift
  KkuMulKum/Source/Home/HomeViewController.swift
  KkuMulKum/Source/Home/Model/UpcomingPromiseModel.swift
  KkuMulKum/Source/Home/View/HomeView.swift
  KkuMulKum/Source/Home/View/TodayEmptyView.swift
  KkuMulKum/Source/Home/View/TodayPromiseView.swift
  KkuMulKum/Source/Home/View/UpcomingEmptyView.swift
  KkuMulKum/Source/Home/ViewController/HomeViewController.swift
  KkuMulKum/Source/Home/ViewModel/HomeViewModel.swift
Labels: ✨ feat, ❤️ SuYeon

#175 [feat] 지각 꾸물이 뷰 구현
  KkuMulKum.xcodeproj/project.pbxproj
  KkuMulKum/Network/DTO/Model/Promises/PromiseLateInfoResponseModel.swift
  KkuMulKum/Network/DTO/Model/Promises/TardyInfoModel.swift
  KkuMulKum/Resource/Assets.xcassets/Image/img_empty_tardy.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/Image/img_empty_tardy.imageset/img_empty_tardy.svg
  KkuMulKum/Resource/Assets.xcassets/Image/img_gift.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/Image/img_gift.imageset/img_gift.svg
  KkuMulKum/Resource/Assets.xcassets/Image/img_splash.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/Image/img_splash.imageset/img_splash.svg
  KkuMulKum/Resource/Base/BaseViewController.swift
  KkuMulKum/Source/Core/MainTabBarController.swift
  KkuMulKum/Source/MeetingCreate/InviteCode/ViewController/InviteCodeViewController.swift
  KkuMulKum/Source/MeetingList/View/MeetingListView.swift
  KkuMulKum/Source/MeetingList/ViewController/MeetingListViewController.swift
  KkuMulKum/Source/Onboarding/Login/ViewController/LoginViewController.swift
  KkuMulKum/Source/Promise/PagePromise/View/PagePromiseSegmentedControl.swift
  KkuMulKum/Source/Promise/PagePromise/ViewController/PagePromiseViewController.swift
  KkuMulKum/Source/Promise/PagePromise/ViewModel/PagePromiseViewModel.swift
  KkuMulKum/Source/Promise/PromiseInfo/View/PromiseInfoView.swift
  KkuMulKum/Source/Promise/Tardy/Cell/TardyCollectionViewCell.swift
  KkuMulKum/Source/Promise/Tardy/Service/TardyService.swift
  KkuMulKum/Source/Promise/Tardy/View/ArriveView.swift
  KkuMulKum/Source/Promise/Tardy/View/TardyEmptyView.swift
  KkuMulKum/Source/Promise/Tardy/View/TardyPenaltyView.swift
  KkuMulKum/Source/Promise/Tardy/View/TardyView.swift
  KkuMulKum/Source/Promise/Tardy/ViewController/TardyViewController.swift
  KkuMulKum/Source/Promise/Tardy/ViewModel/TardyViewModel.swift
Labels: ✨ feat, 💚 YouJin

#179 [feat] 준비 정보 입력 UI 구현
  KkuMulKum.xcodeproj/project.pbxproj
  KkuMulKum/Network/DTO/ResponseBody/ResponseBodyDTO.swift
  KkuMulKum/Resource/Component/CustomTextField.swift
  KkuMulKum/Resource/Util/Toast.swift
  KkuMulKum/Source/Home/View/TodayPromiseView.swift
  KkuMulKum/Source/Home/ViewController/HomeViewController.swift
  KkuMulKum/Source/Promise/ReadyStatus/View/SetReadyInfoView.swift
  KkuMulKum/Source/Promise/ReadyStatus/ViewController/SetReadyInfoViewController.swift
  KkuMulKum/Source/Promise/ReadyStatus/ViewModel/SetReadyInfoViewModel.swift
Labels: ✨ feat, ❤️ SuYeon

#180 [Feat] 소셜로그인 구현
  KkuMulKum.xcodeproj/project.pbxproj
  KkuMulKum/Network/DTO/Model/Auth/SocialLoginRequestModel.swift
  KkuMulKum/Network/DTO/Model/Auth/SocialLoginResponseModel.swift
  KkuMulKum/Network/DTO/ResponseBody/ResponseBodyDTO.swift
  KkuMulKum/Network/DTO/TargetType/LoginTargetType.swift
  KkuMulKum/Resource/Bundle/Bundle.swift
  KkuMulKum/Source/Onboarding/Login/VIewModel/LoginViewModel.swift
  KkuMulKum/Source/Onboarding/Login/ViewController/LoginViewController.swift
Labels: ✨ feat, 🧡 JiHoon

#177 [Feat] AuthService 구현
  KkuMulKum.xcodeproj/project.pbxproj
  KkuMulKum/Source/Onboarding/Login/Service/AuthService.swift
  KkuMulKum/Source/Onboarding/Login/VIewModel/LoginViewModel.swift
  KkuMulKum/Source/Onboarding/Login/ViewController/LoginViewController.swift
  KkuMulKum/Source/Onboarding/Profile/VIewController/ProfileSetupViewController.swift
  KkuMulKum/Source/Onboarding/Profile/View/ProfileSetupView.swift
  KkuMulKum/Source/Onboarding/Profile/ViewModel/ProfileSetupViewModel.swift
  KkuMulKum/Source/Onboarding/Welcome/View/WelcomeView.swift
Labels: ✨ feat, 🧡 JiHoon

#184 [feat] 내 모임 화면 서비스 타입 구현 및 디자인 QA 반영
  KkuMulKum.xcodeproj/project.pbxproj
  KkuMulKum.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  KkuMulKum/Network/DTO/Model/Meetings/RegisterMeetingsResquestModel.swift
  KkuMulKum/Resource/Service/MeetingListService.swift
  KkuMulKum/Source/Core/MainTabBarController.swift
  KkuMulKum/Source/Home/View/UpcomingPromiseCollecitonViewCell.swift
  KkuMulKum/Source/MeetingList/Model/MeetingDummyModel.swift
  KkuMulKum/Source/MeetingList/View/MeetingListView.swift
  KkuMulKum/Source/MeetingList/View/MeetingTableViewCell.swift
  KkuMulKum/Source/MeetingList/ViewController/MeetingListViewController.swift
  KkuMulKum/Source/MeetingList/ViewModel/MeetingListViewModel.swift
Labels: 🛠️ fix, ❤️ SuYeon

#183 [Feat] make keychain
  KkuMulKum.xcodeproj/project.pbxproj
  KkuMulKum/Application/AppDelegate.swift
  KkuMulKum/KkuMulKum.entitlements
  KkuMulKum/Network/DTO/Model/Auth/SocialLoginResponseModel.swift
  KkuMulKum/Network/DTO/TargetType/LoginTargetType.swift
  KkuMulKum/Resource/KeyChain/KeychainAccessible.swift
  KkuMulKum/Resource/KeyChain/KeychainService.swift
  KkuMulKum/Source/Onboarding/Login/Service/AuthService.swift
  KkuMulKum/Source/Onboarding/Login/VIewModel/LoginViewModel.swift
  KkuMulKum/Source/Onboarding/Login/ViewController/LoginViewController.swift
Labels: ✨ feat, 🧡 JiHoon

#189 [refactor] 전체적인 컨벤션 조정
  KkuMulKum.xcodeproj/project.pbxproj
  KkuMulKum.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  KkuMulKum/Resource/Assets.xcassets/AccentColor.colorset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/AppIcon.appiconset/app_icon.png
  KkuMulKum/Resource/Assets.xcassets/AppIcon.appiconset/appstore.png
  KkuMulKum/Source/MeetingCreate/CheckInviteCode/View/CheckInviteCodeView.swift
  KkuMulKum/Source/MeetingCreate/CheckInviteCode/View/JoinButtonView.swift
  KkuMulKum/Source/MeetingCreate/CheckInviteCode/ViewController/CheckInviteCodeViewController.swift
  KkuMulKum/Source/MeetingCreate/CreateMeeting/View/CreateMeetingView.swift
  KkuMulKum/Source/MeetingCreate/CreateMeeting/ViewController/CreateMeetingViewController.swift
  KkuMulKum/Source/MeetingCreate/CreateMeeting/ViewModel/CreateMeetingViewModel.swift
  KkuMulKum/Source/MeetingCreate/FinishCreate/View/FinishCreateNavigationView.swift
  KkuMulKum/Source/MeetingCreate/FinishCreate/ViewController/FinishCreateViewController.swift
  KkuMulKum/Source/MeetingCreate/InviteCode/View/InviteCodeView.swift
  KkuMulKum/Source/MeetingCreate/InviteCode/ViewController/InviteCodeViewController.swift
  KkuMulKum/Source/MeetingCreate/InviteCode/ViewModel/InviteCodeViewModel.swift
  KkuMulKum/Source/Promise/PagePromise/View/PagePromiseSegmentedControl.swift
  KkuMulKum/Source/Promise/PagePromise/ViewController/PagePromiseViewController.swift
  KkuMulKum/Source/Promise/PagePromise/ViewModel/PagePromiseViewModel.swift
  KkuMulKum/Source/Promise/PromiseInfo/Cell/ParticipantCollectionViewCell.swift
  KkuMulKum/Source/Promise/PromiseInfo/View/PromiseInfoView.swift
  KkuMulKum/Source/Promise/PromiseInfo/ViewController/PromiseInfoViewController.swift
  KkuMulKum/Source/Promise/ReadyStatus/View/EnterReadyInfoButtonView.swift
  KkuMulKum/Source/Promise/ReadyStatus/View/ReadyPlanInfoView.swift
  KkuMulKum/Source/Promise/Tardy/Cell/TardyCollectionViewCell.swift
  KkuMulKum/Source/Promise/Tardy/Service/TardyService.swift
  KkuMulKum/Source/Promise/Tardy/View/ArriveView.swift
  KkuMulKum/Source/Promise/Tardy/View/TardyEmptyView.swift
  KkuMulKum/Source/Promise/Tardy/View/TardyPenaltyView.swift
  KkuMulKum/Source/Promise/Tardy/View/TardyView.swift
  KkuMulKum/Source/Promise/Tardy/ViewController/TardyViewController.swift
  KkuMulKum/Source/Promise/Tardy/ViewModel/TardyViewModel.swift
Labels: 🛠️ fix, ♻️ refactor, 💚 YouJin

#191 [Feat] 닉네임 api 연결
  KkuMulKum.xcodeproj/project.pbxproj
  KkuMulKum/KkuMulKumDebug.entitlements
  KkuMulKum/Network/DTO/Model/Auth/NicknameModel.swift
  KkuMulKum/Network/DTO/Model/Auth/ProfileModel.swift
  KkuMulKum/Network/DTO/TargetType/NicknameTargetType.swift
  KkuMulKum/Network/DTO/TargetType/ProfileTargetType.swift
  KkuMulKum/Resource/Info.plist
  KkuMulKum/Resource/KeyChain/KeychainAccessible.swift
  KkuMulKum/Resource/KeyChain/KeychainService.swift
  KkuMulKum/Resource/Service/AuthService.swift
  KkuMulKum/Source/Onboarding/Login/VIewModel/LoginViewModel.swift
  KkuMulKum/Source/Onboarding/Login/ViewController/LoginViewController.swift
  KkuMulKum/Source/Onboarding/Nickname/ViewController/NicknameViewController.swift
  KkuMulKum/Source/Onboarding/Nickname/ViewModel/NicknameViewModel.swift
  KkuMulKum/Source/Onboarding/Profile/VIewController/ProfileSetupViewController.swift
  KkuMulKum/Source/Onboarding/Profile/ViewModel/ProfileSetupViewModel.swift
  KkuMulKum/Source/Promise/PagePromise/ViewModel/PagePromiseViewModel.swift
  KkuMulKum/Source/Promise/ReadyStatus/ViewController/ReadyStatusViewController.swift
Labels: ✨ feat, 🧡 JiHoon

#194 [feat] FCM 토큰 받아오기 추가
  KkuMulKum.xcodeproj/project.pbxproj
  KkuMulKum/Application/AppDelegate.swift
  KkuMulKum/KkuMulKum.entitlements
  KkuMulKum/Resource/GoogleService-Info.plist
  KkuMulKum/Resource/Info.plist
Labels: ✨ feat, 🧡 JiHoon

#192 [Feat] 서비스 타입 구현
  KkuMulKum.xcodeproj/project.pbxproj
  KkuMulKum/Source/MeetingCreate/CheckInviteCode/ViewController/CheckInviteCodeViewController.swift
  KkuMulKum/Source/MeetingCreate/CreateMeeting/Service/CreateMeetingService.swift
  KkuMulKum/Source/MeetingCreate/CreateMeeting/Service/MockCreateMeetingService.swift
  KkuMulKum/Source/MeetingCreate/CreateMeeting/ViewModel/CreateMeetingViewModel.swift
  KkuMulKum/Source/MeetingCreate/InviteCode/Service/InviteCodeService.swift
  KkuMulKum/Source/MeetingCreate/InviteCode/ViewModel/InviteCodeViewModel.swift
  KkuMulKum/Source/Promise/PagePromise/ViewController/PagePromiseViewController.swift
  KkuMulKum/Source/Promise/PromiseInfo/Service/PromiseInfoService.swift
  KkuMulKum/Source/Promise/PromiseInfo/ViewModel/PromiseInfoViewModel.swift
  KkuMulKum/Source/Promise/ReadyStatus/Service/ReadyStatusService.swift
  KkuMulKum/Source/Promise/ReadyStatus/ViewModel/ReadyStatusViewModel.swift
  KkuMulKum/Source/Promise/Tardy/Service/TardyService.swift
  KkuMulKum/Source/Promise/Tardy/ViewModel/TardyViewModel.swift
Labels: ✨ feat, 💚 YouJin

#196 [feat] 약속 추가 플로우 구현
  KkuMulKum.xcodeproj/project.pbxproj
  KkuMulKum/Application/SceneDelegate.swift
  KkuMulKum/Network/DTO/Model/Promises/AddPromiseRequestModel.swift
  KkuMulKum/Network/DTO/Model/Promises/AddPromiseResponseModel.swift
  KkuMulKum/Network/DTO/Model/Utils/PlaceModel.swift
  KkuMulKum/Network/DTO/Model/Utils/UtilsTemp.swift
  KkuMulKum/Resource/Assets.xcassets/Image/img_Completion.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/Image/img_Completion.imageset/img_Completion.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_Completion.imageset/img_Completion@2x.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_Completion.imageset/img_Completion@3x.png
  KkuMulKum/Source/AddPromise/Cell/PlaceListCell.swift
  KkuMulKum/Source/AddPromise/Cell/SelectMemberCell.swift
  KkuMulKum/Source/AddPromise/Service/FindPlaceService.swift
  KkuMulKum/Source/AddPromise/Service/SelectMemeberServiceType.swift
  KkuMulKum/Source/AddPromise/Service/SelectPenaltyService.swift
  KkuMulKum/Source/AddPromise/View/AddPromiseCompleteView.swift
  KkuMulKum/Source/AddPromise/View/AddPromiseView.swift
  KkuMulKum/Source/AddPromise/View/FindPlaceView.swift
  KkuMulKum/Source/AddPromise/View/SelectCapsuleButton.swift
  KkuMulKum/Source/AddPromise/View/SelectMemberView.swift
  KkuMulKum/Source/AddPromise/View/SelectPenaltyView.swift
  KkuMulKum/Source/AddPromise/ViewController/AddPromiseCompleteViewController.swift
  KkuMulKum/Source/AddPromise/ViewController/AddPromiseViewController.swift
  KkuMulKum/Source/AddPromise/ViewController/FindPlaceViewController.swift
  KkuMulKum/Source/AddPromise/ViewController/SelectMemberViewController.swift
  KkuMulKum/Source/AddPromise/ViewController/SelectPenaltyViewController.swift
  KkuMulKum/Source/AddPromise/ViewModel/AddPromiseViewModel.swift
  KkuMulKum/Source/AddPromise/ViewModel/FindPlaceViewModel.swift
  KkuMulKum/Source/AddPromise/ViewModel/SelectMemberViewModel.swift
  KkuMulKum/Source/AddPromise/ViewModel/SelectPenaltyViewModel.swift
  KkuMulKum/Source/Core/MainTabBarController.swift
  KkuMulKum/Source/MeetingInfo/Cell/MeetingMemberCell.swift
  KkuMulKum/Source/MeetingInfo/Cell/MeetingPromiseCell.swift
  KkuMulKum/Source/MeetingInfo/ViewController/InvitationCodePopUpViewController.swift
  KkuMulKum/Source/MeetingInfo/ViewController/MeetingInfoViewController.swift
  KkuMulKum/Source/MeetingInfo/ViewModel/MeetingInfoViewModel.swift
  KkuMulKum/Source/MeetingList/ViewController/MeetingListViewController.swift
  KkuMulKum/Source/Onboarding/Login/ViewController/LoginViewController.swift
  KkuMulKum/Source/Onboarding/Welcome/ViewController/WelcomeViewController.swift
Labels: ✨ feat, 💙 JinUng

#193 [feat] 홈 화면 서비스 타입 구현 및 뷰모델 로직 수정
  KkuMulKum.xcodeproj/project.pbxproj
  KkuMulKum/Resource/Assets.xcassets/Image/img_level01.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/Image/img_level01.imageset/level01.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_level01.imageset/level01@2x.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_level01.imageset/level01@3x.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_level02.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/Image/img_level02.imageset/level02.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_level02.imageset/level02@2x.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_level02.imageset/level02@3x.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_level03.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/Image/img_level03.imageset/level03.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_level03.imageset/level03@2x.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_level03.imageset/level03@3x.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_level04.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/Image/img_level04.imageset/level04.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_level04.imageset/level04@2x.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_level04.imageset/level04@3x.png
  KkuMulKum/Resource/Service/HomeService.swift
  KkuMulKum/Resource/Service/MeetingListService.swift
  KkuMulKum/Source/Core/MainTabBarController.swift
  KkuMulKum/Source/Home/Model/UpcomingPromiseModel.swift
  KkuMulKum/Source/Home/View/HomeView.swift
  KkuMulKum/Source/Home/View/TodayPromiseView.swift
  KkuMulKum/Source/Home/View/UpcomingPromiseCollecitonViewCell.swift
  KkuMulKum/Source/Home/ViewController/HomeViewController.swift
  KkuMulKum/Source/Home/ViewModel/HomeViewModel.swift
  KkuMulKum/Source/MeetingList/ViewController/MeetingListViewController.swift
  KkuMulKum/Source/MeetingList/ViewModel/MeetingListViewModel.swift
Labels: ✨ feat, 🛠️ fix, ❤️ SuYeon

#202 [feat] local notification
  KkuMulKum.xcodeproj/project.pbxproj
  KkuMulKum/Resource/Notification/LocalNotificationManager.swift
Labels: ✨ feat, 🧡 JiHoon

#203 [feat] Meeting TargetType 구현
  KkuMulKum.xcodeproj/project.pbxproj
  KkuMulKum/Network/DTO/TargetType/MeetingTargetType.swift
Labels: ✨ feat, 💚 YouJin

#201 [feat] 준비 정보 입력 완료 화면 구현
  KkuMulKum.xcodeproj/project.pbxproj
  KkuMulKum/Resource/Assets.xcassets/Image/img_complete.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/Image/img_complete.imageset/complete.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_complete.imageset/complete@2x.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_complete.imageset/complete@3x.png
  KkuMulKum/Resource/Service/HomeService.swift
  KkuMulKum/Source/Promise/ReadyStatus/View/SetReadyCompletedView.swift
  KkuMulKum/Source/Promise/ReadyStatus/ViewController/SetReadyCompletedViewController.swift
Labels: ✨ feat, ❤️ SuYeon

#206 [refactor] API 명세 반영 모델 리팩토링
  KkuMulKum.xcodeproj/project.pbxproj
  KkuMulKum/Network/DTO/Model/Auth/ProfileModel.swift
  KkuMulKum/Network/DTO/Model/Auth/ReissueModel.swift
  KkuMulKum/Network/DTO/Model/Auth/SocialLoginRequestModel.swift
  KkuMulKum/Network/DTO/Model/Auth/SocialLoginResponseModel.swift
  KkuMulKum/Network/DTO/Model/Meetings/MakeMeetingsRequestModel.swift
  KkuMulKum/Network/DTO/Model/Meetings/MakeMeetingsResponseModel.swift
  KkuMulKum/Network/DTO/Model/Meetings/MeetingInfoResponseModel.swift
  KkuMulKum/Network/DTO/Model/Meetings/MeetingListResponseModel.swift
  KkuMulKum/Network/DTO/Model/Meetings/MeetingMembersResponseModel.swift
  KkuMulKum/Network/DTO/Model/Meetings/RegisterMeetingsResquestModel.swift
  KkuMulKum/Network/DTO/Model/Promises/AddPromiseRequestModel.swift
  KkuMulKum/Network/DTO/Model/Promises/AddPromiseResponseModel.swift
  KkuMulKum/Network/DTO/Model/Promises/MeetingPromisesModel.swift
  KkuMulKum/Network/DTO/Model/Promises/MyReadyStatusResponseModel.swift
  KkuMulKum/Network/DTO/Model/Promises/PromiseInfoResponseModel.swift
  KkuMulKum/Network/DTO/Model/Promises/TardyInfoModel.swift
  KkuMulKum/Network/DTO/Model/Promises/UpcomingPromiseListResponseModel.swift
  KkuMulKum/Network/DTO/Model/Users/LoginUserResponseModel.swift
  KkuMulKum/Network/DTO/Model/Users/UpdateProfileNameModel.swift
  KkuMulKum/Network/DTO/Model/Utils/PlaceModel.swift
  KkuMulKum/Resource/Service/HomeService.swift
  KkuMulKum/Resource/Service/MeetingListService.swift
  KkuMulKum/Source/AddPromise/Cell/SelectMemberCell.swift
  KkuMulKum/Source/AddPromise/Service/SelectMemeberServiceType.swift
  KkuMulKum/Source/AddPromise/ViewModel/SelectMemberViewModel.swift
  KkuMulKum/Source/AddPromise/ViewModel/SelectPenaltyViewModel.swift
  KkuMulKum/Source/MeetingInfo/Cell/MeetingMemberCell.swift
  KkuMulKum/Source/MeetingInfo/Service/MeetingInfoService.swift
  KkuMulKum/Source/MeetingInfo/ViewModel/MeetingInfoViewModel.swift
  KkuMulKum/Source/Onboarding/Profile/ViewModel/ProfileSetupViewModel.swift
  KkuMulKum/Source/Promise/ReadyStatus/Service/ReadyStatusService.swift
Labels: ♻️ refactor, 💙 JinUng

#209 [feat] PromiseTargetType 구현
  KkuMulKum.xcodeproj/project.pbxproj
  KkuMulKum/Network/DTO/TargetType/MeetingTargetType.swift
  KkuMulKum/Network/DTO/TargetType/PromiseTargetType.swift
Labels: ✨ feat, 💚 YouJin

#212 [feat] TargetType 구현 및 서비스 기초 세팅
  KkuMulKum.xcodeproj/project.pbxproj
  KkuMulKum/Network/Service/AuthService.swift
  KkuMulKum/Network/Service/HomeService.swift
  KkuMulKum/Network/Service/MeetingService.swift
  KkuMulKum/Network/Service/PromiseService.swift
  KkuMulKum/Network/Service/UtilService.swift
  KkuMulKum/Network/TargetType/HomeTargetType.swift
  KkuMulKum/Network/TargetType/LoginTargetType.swift
  KkuMulKum/Network/TargetType/MeetingTargetType.swift
  KkuMulKum/Network/TargetType/NicknameTargetType.swift
  KkuMulKum/Network/TargetType/ProfileTargetType.swift
  KkuMulKum/Network/TargetType/PromiseTargetType.swift
  KkuMulKum/Network/TargetType/UtilTargetType.swift
  KkuMulKum/Source/AddPromise/ServiceType/FindPlaceService.swift
  KkuMulKum/Source/AddPromise/ServiceType/SelectMemeberServiceType.swift
  KkuMulKum/Source/AddPromise/ServiceType/SelectPenaltyService.swift
  KkuMulKum/Source/Home/ServiceType/HomeServiceType.swift
  KkuMulKum/Source/MeetingList/ServiceType/MeetingListServiceType.swift
  KkuMulKum/Source/Promise/PromiseInfo/Service/PromiseInfoService.swift
Labels: ✨ feat, 💚 YouJin

#217 [feat] FCM 서버 -> 로컬 알람 구현
  KkuMulKum/Application/AppDelegate.swift
  KkuMulKum/Source/Onboarding/Login/VIewModel/LoginViewModel.swift
Labels: ✨ feat, 🧡 JiHoon

#219 [feat] 모임 상세 (MeetingInfo) 화면 네트워크 연결
  KkuMulKum/Network/DTO/Model/Meetings/MeetingMembersResponseModel.swift
  KkuMulKum/Network/DTO/Model/Promises/MeetingPromisesModel.swift
  KkuMulKum/Network/Service/HomeService.swift
  KkuMulKum/Network/Service/MeetingService.swift
  KkuMulKum/Network/Service/PromiseService.swift
  KkuMulKum/Network/Service/UtilService.swift
  KkuMulKum/Network/TargetType/MeetingTargetType.swift
  KkuMulKum/Network/TargetType/PromiseTargetType.swift
  KkuMulKum/Source/AddPromise/Cell/SelectMemberCell.swift
  KkuMulKum/Source/MeetingInfo/Cell/MeetingMemberCell.swift
  KkuMulKum/Source/MeetingInfo/Service/MeetingInfoService.swift
  KkuMulKum/Source/MeetingInfo/ViewController/MeetingInfoViewController.swift
  KkuMulKum/Source/MeetingInfo/ViewModel/MeetingInfoViewModel.swift
  KkuMulKum/Source/MeetingList/ViewController/MeetingListViewController.swift
Labels: ✨ feat, 💙 JinUng

#222 [refactor] 모임 상세에서 약속 상세로 이동하기 위한 코드 리팩토링
  KkuMulKum/Source/MeetingInfo/Cell/MeetingPromiseCell.swift
  KkuMulKum/Source/MeetingInfo/ViewController/MeetingInfoViewController.swift
Labels: ♻️ refactor, 💙 JinUng

#230 [feat] 약속 추가 플로우 네트워크 연결
  KkuMulKum/Network/DTO/Model/Utils/PlaceModel.swift
  KkuMulKum/Network/Service/HomeService.swift
  KkuMulKum/Network/Service/MeetingService.swift
  KkuMulKum/Network/Service/PromiseService.swift
  KkuMulKum/Network/Service/UtilService.swift
  KkuMulKum/Network/TargetType/UtilTargetType.swift
  KkuMulKum/Source/AddPromise/ServiceType/FindPlaceService.swift
  KkuMulKum/Source/AddPromise/ServiceType/SelectMemeberServiceType.swift
  KkuMulKum/Source/AddPromise/ServiceType/SelectPenaltyService.swift
  KkuMulKum/Source/AddPromise/View/FindPlaceView.swift
  KkuMulKum/Source/AddPromise/ViewController/AddPromiseViewController.swift
  KkuMulKum/Source/AddPromise/ViewModel/FindPlaceViewModel.swift
  KkuMulKum/Source/AddPromise/ViewModel/SelectMemberViewModel.swift
  KkuMulKum/Source/AddPromise/ViewModel/SelectPenaltyViewModel.swift
  KkuMulKum/Source/Promise/PagePromise/ViewController/PagePromiseViewController.swift
Labels: ✨ feat, 💙 JinUng

#224 [refactor] Rxswift 도입
  KkuMulKum.xcodeproj/project.pbxproj
  KkuMulKum/Resource/KeyChain/KeychainAccessible.swift
  KkuMulKum/Source/Onboarding/Login/ViewController/LoginViewController.swift
  KkuMulKum/Source/Onboarding/Nickname/View/NicknameView.swift
  KkuMulKum/Source/Onboarding/Nickname/ViewController/NicknameViewController.swift
  KkuMulKum/Source/Onboarding/Nickname/ViewModel/NicknameViewModel.swift
  KkuMulKum/Source/Onboarding/Profile/VIewController/ProfileSetupViewController.swift
  KkuMulKum/Source/Onboarding/Profile/ViewModel/ProfileSetupViewModel.swift
Labels: ✨ feat, 🧡 JiHoon

#232 [feat] 모임 생성, 가입, 약속 상세 화면 연결 및 로직 연결 구현
  KkuMulKum.xcodeproj/project.pbxproj
  KkuMulKum/Resource/Assets.xcassets/Image/img_empty_cell.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/Image/img_empty_cell.imageset/img_empty_cell.svg
  KkuMulKum/Source/AddPromise/ViewController/AddPromiseCompleteViewController.swift
  KkuMulKum/Source/Home/ViewController/HomeViewController.swift
  KkuMulKum/Source/MeetingCreate/CheckInviteCode/ViewController/CheckInviteCodeViewController.swift
  KkuMulKum/Source/MeetingCreate/CreateMeeting/ViewController/CreateMeetingViewController.swift
  KkuMulKum/Source/MeetingCreate/FinishCreate/ViewController/FinishCreateViewController.swift
  KkuMulKum/Source/MeetingCreate/InviteCode/ViewController/InviteCodeViewController.swift
  KkuMulKum/Source/MeetingInfo/View/InvitationCodePopUpView.swift
  KkuMulKum/Source/MeetingInfo/ViewController/InvitationCodePopUpViewController.swift
  KkuMulKum/Source/MeetingInfo/ViewController/MeetingInfoViewController.swift
  KkuMulKum/Source/MeetingList/ViewController/MeetingListViewController.swift
  KkuMulKum/Source/Onboarding/Nickname/ViewModel/NicknameViewModel.swift
  KkuMulKum/Source/Onboarding/Profile/VIewController/ProfileSetupViewController.swift
  KkuMulKum/Source/Onboarding/Profile/ViewModel/ProfileSetupViewModel.swift
  KkuMulKum/Source/Promise/PagePromise/ViewController/PagePromiseViewController.swift
  KkuMulKum/Source/Promise/PagePromise/ViewModel/PagePromiseViewModel.swift
  KkuMulKum/Source/Promise/PromiseInfo/Cell/ParticipantCollectionViewCell.swift
  KkuMulKum/Source/Promise/PromiseInfo/ViewController/PromiseInfoViewController.swift
  KkuMulKum/Source/Promise/PromiseInfo/ViewModel/PromiseInfoViewModel.swift
  KkuMulKum/Source/Promise/ReadyStatus/Service/MockReadyStatusService.swift
  KkuMulKum/Source/Promise/ReadyStatus/View/ReadyStatusView.swift
  KkuMulKum/Source/Promise/ReadyStatus/ViewController/ReadyStatusViewController.swift
  KkuMulKum/Source/Promise/ReadyStatus/ViewController/SetReadyInfoViewController.swift
  KkuMulKum/Source/Promise/ReadyStatus/ViewModel/ReadyStatusViewModel.swift
  KkuMulKum/Source/Promise/Tardy/View/ArriveView.swift
  KkuMulKum/Source/Promise/Tardy/View/TardyView.swift
  KkuMulKum/Source/Promise/Tardy/ViewController/TardyViewController.swift
  KkuMulKum/Source/Promise/Tardy/ViewModel/TardyViewModel.swift
Labels: ✨ feat, 💚 YouJin

#233 [feat] 홈 화면 및 내 모임 리스트 화면 API 연결
  KkuMulKum/Resource/Assets.xcassets/Image/img_empty.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/Image/img_empty.imageset/empty.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_empty.imageset/empty@2x.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_empty.imageset/empty@3x.png
  KkuMulKum/Source/Core/MainTabBarController.swift
  KkuMulKum/Source/Home/ServiceType/HomeServiceType.swift
  KkuMulKum/Source/Home/View/HomeView.swift
  KkuMulKum/Source/Home/ViewController/HomeViewController.swift
  KkuMulKum/Source/Home/ViewModel/HomeViewModel.swift
  KkuMulKum/Source/MeetingList/ServiceType/MeetingListServiceType.swift
  KkuMulKum/Source/MeetingList/View/MeetingListView.swift
  KkuMulKum/Source/MeetingList/ViewController/MeetingListViewController.swift
  KkuMulKum/Source/MeetingList/ViewModel/MeetingListViewModel.swift
Labels: ✨ feat, 🛠️ fix, ❤️ SuYeon

#237 [hotfix] 이미지 업로드 용량 수정
  KkuMulKum.xcodeproj/project.pbxproj
  KkuMulKum/Network/Service/AuthService.swift
  KkuMulKum/Network/TargetType/Auth/AuthError.swift
  KkuMulKum/Network/TargetType/Auth/AuthTargetType.swift
  KkuMulKum/Network/TargetType/LoginTargetType.swift
  KkuMulKum/Network/TargetType/NicknameTargetType.swift
  KkuMulKum/Network/TargetType/ProfileTargetType.swift
  KkuMulKum/Source/Core/Auth/AuthInterceptor.swift
  KkuMulKum/Source/Onboarding/Login/VIewModel/LoginViewModel.swift
  KkuMulKum/Source/Onboarding/Nickname/ViewModel/NicknameViewModel.swift
  KkuMulKum/Source/Onboarding/Profile/ViewModel/ProfileSetupViewModel.swift
Labels: ✨ feat, 🛠️ fix, 💚 YouJin, 🧡 JiHoon

#238 [feat] 준비 정보 입력 화면 연결 및 API 연결
  KkuMulKum.xcodeproj/project.pbxproj
  KkuMulKum/Network/TargetType/PromiseTargetType.swift
  KkuMulKum/Source/Home/ViewController/HomeViewController.swift
  KkuMulKum/Source/MeetingList/ViewModel/MeetingListViewModel.swift
  KkuMulKum/Source/Promise/ReadyStatus/Service/SetReadyStatusInfoServiceType.swift
  KkuMulKum/Source/Promise/ReadyStatus/View/SetReadyCompletedView.swift
  KkuMulKum/Source/Promise/ReadyStatus/ViewController/ReadyStatusViewController.swift
  KkuMulKum/Source/Promise/ReadyStatus/ViewController/SetReadyCompletedViewController.swift
  KkuMulKum/Source/Promise/ReadyStatus/ViewController/SetReadyInfoViewController.swift
  KkuMulKum/Source/Promise/ReadyStatus/ViewModel/SetReadyInfoViewModel.swift
Labels: ✨ feat, ❤️ SuYeon

#239 [feat] 모임 가입 및 생성 API 연결
  KkuMulKum.xcodeproj/project.pbxproj
  KkuMulKum/Network/DTO/Model/Meetings/RegisterMeetingsResponseModel.swift
  KkuMulKum/Resource/Component/CustomTextField.swift
  KkuMulKum/Source/MeetingCreate/CheckInviteCode/ViewController/CheckInviteCodeViewController.swift
  KkuMulKum/Source/MeetingCreate/CreateMeeting/Service/CreateMeetingService.swift
  KkuMulKum/Source/MeetingCreate/CreateMeeting/Service/MockCreateMeetingService.swift
  KkuMulKum/Source/MeetingCreate/CreateMeeting/ViewController/CreateMeetingViewController.swift
  KkuMulKum/Source/MeetingCreate/CreateMeeting/ViewModel/CreateMeetingViewModel.swift
  KkuMulKum/Source/MeetingCreate/InviteCode/Service/InviteCodeService.swift
  KkuMulKum/Source/MeetingCreate/InviteCode/ViewController/InviteCodeViewController.swift
  KkuMulKum/Source/MeetingCreate/InviteCode/ViewModel/InviteCodeViewModel.swift
  KkuMulKum/Source/MeetingInfo/View/InvitationCodePopUpView.swift
  KkuMulKum/Source/Promise/ReadyStatus/View/EnterReadyInfoButtonView.swift
  KkuMulKum/Source/Promise/ReadyStatus/ViewController/ReadyStatusViewController.swift
Labels: ✨ feat, 💚 YouJin

#243 [fix] 네비게이션 Pop 제스처 해결
  KkuMulKum/Resource/Base/BaseViewController.swift
Labels: 🛠️ fix, 💙 JinUng

#244 [feat] 약속 정보 및 지각 현황 API 연결
  KkuMulKum.xcodeproj/project.pbxproj
  KkuMulKum/Application/SceneDelegate.swift
  KkuMulKum/Network/DTO/Model/Promises/MyReadyStatusResponseModel.swift
  KkuMulKum/Network/DTO/Model/Promises/PromiseInfoResponseModel.swift
  KkuMulKum/Source/AddPromise/ViewController/AddPromiseCompleteViewController.swift
  KkuMulKum/Source/Home/ViewController/HomeViewController.swift
  KkuMulKum/Source/MeetingInfo/ViewController/MeetingInfoViewController.swift
  KkuMulKum/Source/Promise/PagePromise/Service/PagePromiseServiceType.swift
  KkuMulKum/Source/Promise/PagePromise/ViewController/PagePromiseViewController.swift
  KkuMulKum/Source/Promise/PagePromise/ViewModel/PagePromiseViewModel.swift
  KkuMulKum/Source/Promise/PromiseInfo/Cell/ParticipantCollectionViewCell.swift
  KkuMulKum/Source/Promise/PromiseInfo/Service/PromiseInfoService.swift
  KkuMulKum/Source/Promise/PromiseInfo/View/PromiseInfoView.swift
  KkuMulKum/Source/Promise/PromiseInfo/ViewController/PromiseInfoViewController.swift
  KkuMulKum/Source/Promise/PromiseInfo/ViewModel/PromiseInfoViewModel.swift
  KkuMulKum/Source/Promise/ReadyStatus/Service/ReadyStatusServiceType.swift
  KkuMulKum/Source/Promise/ReadyStatus/View/OurReadyStatusCollectionViewCell.swift
  KkuMulKum/Source/Promise/ReadyStatus/View/ReadyPlanInfoView.swift
  KkuMulKum/Source/Promise/ReadyStatus/View/ReadyStatusButton.swift
  KkuMulKum/Source/Promise/ReadyStatus/View/ReadyStatusView.swift
  KkuMulKum/Source/Promise/ReadyStatus/ViewController/ReadyStatusViewController.swift
  KkuMulKum/Source/Promise/ReadyStatus/ViewModel/ReadyStatusViewModel.swift
  KkuMulKum/Source/Promise/ReadyStatus/ViewModel/SetReadyInfoViewModel.swift
  KkuMulKum/Source/Promise/Tardy/Service/TardyService.swift
Labels: ✨ feat, 💚 YouJin

#246 [feat] Local 알람 구현 완료 + 스크롤뷰 오류 해결
  KkuMulKum/Application/AppDelegate.swift
  KkuMulKum/Resource/Notification/LocalNotificationManager.swift
  KkuMulKum/Source/AddPromise/ViewController/AddPromiseViewController.swift
  KkuMulKum/Source/AddPromise/ViewController/SelectMemberViewController.swift
  KkuMulKum/Source/Promise/ReadyStatus/View/ReadyStatusView.swift
  KkuMulKum/Source/Promise/ReadyStatus/ViewController/ReadyStatusViewController.swift
  KkuMulKum/Source/Promise/ReadyStatus/ViewController/SetReadyInfoViewController.swift
  KkuMulKum/Source/Promise/ReadyStatus/ViewModel/SetReadyInfoViewModel.swift
Labels: ✨ feat, 🧡 JiHoon

#247 [feat] 약속 상세 API 연결
  KkuMulKum/Source/Promise/PagePromise/ViewController/PagePromiseViewController.swift
  KkuMulKum/Source/Promise/ReadyStatus/View/ReadyPlanInfoView.swift
  KkuMulKum/Source/Promise/ReadyStatus/ViewController/ReadyStatusViewController.swift
  KkuMulKum/Source/Promise/ReadyStatus/ViewModel/ReadyStatusViewModel.swift
  KkuMulKum/Source/Promise/Tardy/Cell/TardyCollectionViewCell.swift
  KkuMulKum/Source/Promise/Tardy/View/TardyEmptyView.swift
  KkuMulKum/Source/Promise/Tardy/View/TardyPenaltyView.swift
  KkuMulKum/Source/Promise/Tardy/View/TardyView.swift
  KkuMulKum/Source/Promise/Tardy/ViewController/TardyViewController.swift
  KkuMulKum/Source/Promise/Tardy/ViewModel/TardyViewModel.swift
Labels: ✨ feat, 💚 YouJin

#255 [fix] 약속 추가 Picker 로직 수정
  KkuMulKum/Source/AddPromise/View/AddPromiseView.swift
  KkuMulKum/Source/AddPromise/View/SelectCapsuleButton.swift
  KkuMulKum/Source/AddPromise/ViewController/AddPromiseCompleteViewController.swift
  KkuMulKum/Source/AddPromise/ViewController/AddPromiseViewController.swift
  KkuMulKum/Source/AddPromise/ViewModel/AddPromiseViewModel.swift
Labels: 🛠️ fix, 💙 JinUng

#256 [fix] 약속 추가 플로우 중 멤버 초대 화면, 나를 제외한 멤버 목록 API 반영
  KkuMulKum/Network/TargetType/MeetingTargetType.swift
  KkuMulKum/Network/TargetType/PromiseTargetType.swift
  KkuMulKum/Source/AddPromise/ServiceType/SelectMemeberServiceType.swift
  KkuMulKum/Source/AddPromise/ViewController/AddPromiseViewController.swift
  KkuMulKum/Source/AddPromise/ViewModel/SelectMemberViewModel.swift
Labels: 🛠️ fix, 💙 JinUng

#257 fix/#254 준비현황 레이아웃 수정
  KkuMulKum/Application/SceneDelegate.swift
  KkuMulKum/Source/Onboarding/Profile/ViewModel/ProfileSetupViewModel.swift
  KkuMulKum/Source/Promise/ReadyStatus/View/ReadyStatusView.swift
  KkuMulKum/Source/Promise/ReadyStatus/ViewController/ReadyStatusViewController.swift
Labels: ✨ feat, 🛠️ fix, 🧡 JiHoon

#260 [fix] 홈 화면 엠티뷰 처리 로직 변경
  KkuMulKum/Source/Home/ViewController/HomeViewController.swift
Labels: 🛠️ fix, 💙 JinUng

#262 [feat] 준비 현황 API 구현
  KkuMulKum.xcodeproj/project.pbxproj
  KkuMulKum/Resource/Assets.xcassets/Image/img_empty_tardy.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/Image/img_empty_tardy.imageset/Layer_1.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_empty_tardy.imageset/Layer_1@2x.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_empty_tardy.imageset/Layer_1@3x.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_empty_tardy.imageset/img_empty_tardy.svg
  KkuMulKum/Source/MeetingCreate/CreateMeeting/ViewController/CreateMeetingViewController.swift
  KkuMulKum/Source/Promise/PromiseInfo/Service/PromiseInfoService.swift
  KkuMulKum/Source/Promise/ReadyStatus/Service/ReadyStatusServiceType.swift
  KkuMulKum/Source/Promise/ReadyStatus/View/OurReadyStatusCollectionViewCell.swift
  KkuMulKum/Source/Promise/ReadyStatus/ViewController/ReadyStatusViewController.swift
  KkuMulKum/Source/Promise/ReadyStatus/ViewModel/ReadyStatusViewModel.swift
  KkuMulKum/Source/Promise/Tardy/Cell/TardyCollectionViewCell.swift
  KkuMulKum/Source/Promise/Tardy/Service/TardyService.swift
Labels: ✨ feat, 💚 YouJin

#263 [hotfix/suyeon] QA 이슈 반영
  KkuMulKum/Source/Home/ViewController/HomeViewController.swift
Labels: 🛠️ fix, ❤️ SuYeon

#266 [fix] QA 반영
  KkuMulKum/Source/Promise/ReadyStatus/ViewController/ReadyStatusViewController.swift
  KkuMulKum/Source/Promise/ReadyStatus/ViewModel/ReadyStatusViewModel.swift
Labels: 🛠️ fix, 💚 YouJin

#267 [fix] QA 반영
  KkuMulKum/Source/AddPromise/ViewModel/AddPromiseViewModel.swift
  KkuMulKum/Source/MeetingCreate/CreateMeeting/ViewController/CreateMeetingViewController.swift
  KkuMulKum/Source/Promise/PagePromise/ViewController/PagePromiseViewController.swift
  KkuMulKum/Source/Promise/ReadyStatus/ViewController/ReadyStatusViewController.swift
  KkuMulKum/Source/Promise/Tardy/ViewController/TardyViewController.swift
  KkuMulKum/Source/Promise/Tardy/ViewModel/TardyViewModel.swift
Labels: 🛠️ fix, 💚 YouJin
