Repository OMZigak/KKUYOS, pull requests merged in 2024-06, with the labels that each got.

#46 feat: 수정햇다 수연아 운동가자
  KkuMulKum.xcodeproj/project.xcworkspace/xcuserdata/hoon.xcuserdatad/UserInterfaceState.xcuserstate
  KkuMulKum/ViewController.swift
Labels: question

#69 [Docs] 이슈와 PR 템플릿 추가 및 gitignore 세팅
  .github/ISSUE_TEMPLATE/feature-template.md
  .github/pull_request_template.md
  .gitignore
  KkuMulKum.xcodeproj/project.pbxproj
  KkuMulKum.xcodeproj/project.xcworkspace/xcuserdata/hoon.xcuserdatad/UserInterfaceState.xcuserstate
  KkuMulKum.xcodeproj/xcuserdata/hoon.xcuserdatad/xcschemes/xcschememanagement.plist
Labels: 📝 docs, 💚 YouJiin

#65 add : import library
  .gitignore
  KkuMulKum.xcodeproj/project.pbxproj
  KkuMulKum.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  README.md
Labels: ⚙️ setting, 🧀 add
