Repository OMZigak/KKUYOS, pull requests merged in 2024-09, with the labels that each got.

#354 [fix] 모임 상세 화면 QA 반영하기
  KkuMulKum/Source/MeetingInfo/Cell/MeetingMemberCell.swift
  KkuMulKum/Source/MeetingInfo/View/MeetingInfoBannerView.swift
  KkuMulKum/Source/MeetingInfo/View/MeetingInfoView.swift
  KkuMulKum/Source/MeetingInfo/ViewModel/MeetingInfoViewModel.swift
Labels: 🛠️ fix, 💙 JinUng

#356 [fix] 홈뷰 QA 반영
  KkuMulKum/Source/Home/ViewController/HomeViewController.swift
Labels: 🛠️ fix, ❤️ SuYeon

#360 [feat] 준비 정보 수정 플로우 추가
  KkuMulKum/Source/Promise/ReadyStatus/View/ReadyPlanInfoView.swift
  KkuMulKum/Source/Promise/ReadyStatus/ViewController/ReadyStatusViewController.swift
  KkuMulKum/Source/SetReadyInfo/ViewController/SetReadyInfoViewController.swift
  KkuMulKum/Source/SetReadyInfo/ViewModel/SetReadyInfoViewModel.swift
Labels: ✨ feat, ❤️ SuYeon

#362 [fix] 화면 회전 막기 및 iOS만 지원
  KkuMulKum.xcodeproj/project.pbxproj
  KkuMulKum/Application/AppDelegate.swift
Labels: 🛠️ fix, 💙 JinUng

#364 [fix] 1차 QA 반영
  KkuMulKum/Source/AddMeeting/CheckInviteCode/View/CheckInviteCodeView.swift
  KkuMulKum/Source/AddMeeting/CreateMeeting/View/CreateMeetingView.swift
  KkuMulKum/Source/AddMeeting/CreateMeeting/ViewController/CreateMeetingViewController.swift
  KkuMulKum/Source/AddMeeting/CreateMeeting/ViewModel/CreateMeetingViewModel.swift
  KkuMulKum/Source/AddMeeting/InviteCode/View/InviteCodeView.swift
  KkuMulKum/Source/Promise/EditPromise/ViewController/ChooseContentViewController.swift
  KkuMulKum/Source/Promise/PagePromise/ViewController/PromiseViewController.swift
  KkuMulKum/Source/Promise/PromiseInfo/Cell/ParticipantCollectionViewCell.swift
  KkuMulKum/Source/Promise/PromiseInfo/View/PromiseInfoView.swift
  KkuMulKum/Source/Promise/PromiseInfo/ViewController/PromiseInfoViewController.swift
  KkuMulKum/Source/Promise/ReadyStatus/View/ReadyPlanInfoView.swift
  KkuMulKum/Source/Promise/ReadyStatus/View/ReadyStatusView.swift
  KkuMulKum/Source/Promise/ReadyStatus/ViewController/ReadyStatusViewController.swift
  KkuMulKum/Source/Promise/Tardy/View/TardyView.swift
  KkuMulKum/Source/Promise/Tardy/ViewController/TardyViewController.swift
  KkuMulKum/Source/Promise/ViewModel/PromiseViewModel.swift
Labels: 🛠️ fix, 💚 YouJin

#366 [fix] 최종 QA 반영
  KkuMulKum/Source/Home/ViewController/HomeViewController.swift
  KkuMulKum/Source/MeetingList/ViewController/MeetingListViewController.swift
Labels: 🛠️ fix, ❤️ SuYeon

#369 [fix] 네비게이션바 경계선 로직 수정
  KkuMulKum/Application/SceneDelegate.swift
  KkuMulKum/Resource/Base/BaseViewController.swift
  KkuMulKum/Resource/Extension/UINavigationController+.swift
  KkuMulKum/Source/AddPromise/ViewController/AddPromiseCompleteViewController.swift
  KkuMulKum/Source/AddPromise/ViewController/AddPromiseViewController.swift
  KkuMulKum/Source/AddPromise/ViewController/SelectMemberViewController.swift
  KkuMulKum/Source/AddPromise/ViewController/SelectPenaltyViewController.swift
  KkuMulKum/Source/MeetingInfo/ViewController/MeetingInfoViewController.swift
  KkuMulKum/Source/Onboarding/Login/ViewController/LoginViewController.swift
  KkuMulKum/Source/Onboarding/Welcome/ViewController/WelcomeViewController.swift
  KkuMulKum/Source/Promise/PagePromise/ViewController/PromiseViewController.swift
Labels: 🛠️ fix, 💙 JinUng

#374 [refactor] 모임 내 약속 조회 기능 수정 및 QA 반영
  KkuMulKum.xcodeproj/project.pbxproj
  KkuMulKum/Network/DTO/ResponseBody/ResponseBodyDTO.swift
  KkuMulKum/Network/Service/MeetingService.swift
  KkuMulKum/Resource/Base/BaseViewController.swift
  KkuMulKum/Source/MeetingInfo/Cell/MeetingMemberCell.swift
  KkuMulKum/Source/MeetingInfo/Service/MeetingInfoService.swift
  KkuMulKum/Source/MeetingInfo/View/MeetingInfoView.swift
  KkuMulKum/Source/MeetingInfo/ViewController/MeetingInfoViewController.swift
  KkuMulKum/Source/MeetingInfo/ViewModel/MeetingInfoViewModel.swift
Labels: ♻️ refactor, 💙 JinUng

#370 [fix] 카카오로그인 수정 및 킹피셔 이슈 해결
  KkuMulKum.xcodeproj/project.pbxproj
  KkuMulKum/Resource/Info.plist
  KkuMulKum/Source/MyPage/ViewController/MyPageEditViewController.swift
  KkuMulKum/Source/MyPage/ViewController/MyPageTermsViewController.swift
  KkuMulKum/Source/MyPage/ViewController/MyPageViewController.swift
  KkuMulKum/Source/MyPage/ViewModel/MyPageEditViewModel.swift
  KkuMulKum/Source/Onboarding/Profile/VIewController/ProfileSetupViewController.swift
  KkuMulKum/Source/Onboarding/Profile/ViewModel/ProfileSetupViewModel.swift
Labels: 🛠️ fix, 🧡 JiHoon

#375 [fix] 약속 상세 QA 반영
  KkuMulKum/Source/Promise/EditPromise/ViewController/ChooseContentViewController.swift
  KkuMulKum/Source/Promise/EditPromise/ViewController/ChooseMemberViewController.swift
  KkuMulKum/Source/Promise/PagePromise/ViewController/PromiseViewController.swift
  KkuMulKum/Source/Promise/PromiseInfo/ViewController/PromiseInfoViewController.swift
  KkuMulKum/Source/Promise/ReadyStatus/View/ReadyStatusView.swift
  KkuMulKum/Source/Promise/ReadyStatus/ViewController/ReadyStatusViewController.swift
  KkuMulKum/Source/Promise/Tardy/View/ArriveView.swift
  KkuMulKum/Source/Promise/Tardy/ViewController/TardyViewController.swift
  KkuMulKum/Source/Promise/ViewModel/PromiseViewModel.swift
Labels: 🛠️ fix, 💚 YouJin

#378 [refactor] QA 관련 api 호출 로직 수정
  KkuMulKum/Source/Home/ViewModel/HomeViewModel.swift
Labels: ♻️ refactor, ❤️ SuYeon

#379 [fix] 약속 상세 3차 QA 반영
  KkuMulKum/Source/Promise/EditPromise/ViewController/ChooseMemberViewController.swift
  KkuMulKum/Source/Promise/EditPromise/ViewModel/EditPromiseViewModel.swift
  KkuMulKum/Source/Promise/PagePromise/ViewController/PromiseViewController.swift
  KkuMulKum/Source/Promise/PromiseInfo/ViewController/PromiseInfoViewController.swift
  KkuMulKum/Source/Promise/ReadyStatus/ViewController/ReadyStatusViewController.swift
  KkuMulKum/Source/Promise/ViewModel/PromiseViewModel.swift
Labels: 🛠️ fix, ♻️ refactor, 💚 YouJin

#381 [fix] 망기적꾸물이 오타 수정
  KkuMulKum/Source/MyPage/ViewModel/MyPageViewModel.swift
Labels: 🛠️ fix, 🧡 JiHoon

#385 [fix] 모임 상세 화면 최종 QA 반영
  KkuMulKum/Source/MeetingInfo/Cell/MeetingPromiseCell.swift
Labels: 🛠️ fix, 💙 JinUng

#387 [refactor] ObservablePattern 다중 구독 구현하기
  KkuMulKum/Resource/ObservablePattern/ObservablePattern.swift
  KkuMulKum/Source/Promise/ServiceProtocol/PromiseServiceProtocol.swift
Labels: ♻️ refactor, 💙 JinUng

#389 [Fix] 최종 qa 반영
  KkuMulKum/Application/AppDelegate.swift
  KkuMulKum/Application/SceneDelegate.swift
  KkuMulKum/Source/MyPage/ViewController/MyPageViewController.swift
  KkuMulKum/Source/Onboarding/Profile/VIewController/ProfileSetupViewController.swift
Labels: 🛠️ fix, 🧡 JiHoon

#390 [refactor] 약속 상세(PagePromise, PromiseInfo, ReadyStatus, Tardy) ViewController와 ViewModel 재구현
  KkuMulKum.xcodeproj/project.pbxproj
  KkuMulKum/Resource/ObservablePattern/ObservablePattern.swift
  KkuMulKum/Source/AddMeeting/CreateMeeting/ViewController/CreateMeetingViewController.swift
  KkuMulKum/Source/Promise/EditPromise/ViewController/ChooseContentViewController.swift
  KkuMulKum/Source/Promise/EditPromise/ViewController/EditPromiseViewController.swift
  KkuMulKum/Source/Promise/PagePromise/ViewController/PromiseViewController.swift
  KkuMulKum/Source/Promise/PromiseInfo/View/PromiseInfoView.swift
  KkuMulKum/Source/Promise/PromiseInfo/ViewController/PromiseInfoViewController.swift
  KkuMulKum/Source/Promise/ReadyStatus/Cell/OurReadyStatusCollectionViewCell.swift
  KkuMulKum/Source/Promise/ReadyStatus/View/ReadyPlanInfoView.swift
  KkuMulKum/Source/Promise/ReadyStatus/View/ReadyStatusButton.swift
  KkuMulKum/Source/Promise/ReadyStatus/View/ReadyStatusProgressView.swift
  KkuMulKum/Source/Promise/ReadyStatus/ViewController/ReadyStatusViewController.swift
  KkuMulKum/Source/Promise/Tardy/View/NoTardyView.swift
  KkuMulKum/Source/Promise/Tardy/View/TardyView.swift
  KkuMulKum/Source/Promise/Tardy/ViewController/TardyViewController.swift
  KkuMulKum/Source/Promise/ViewModel/PromiseViewModel.swift
Labels: ✨ feat, 🛠️ fix, ♻️ refactor, 💚 YouJin

#393 [fix] 최종 QA 반영
  KkuMulKum/Source/Promise/ReadyStatus/View/ReadyStatusProgressView.swift
  KkuMulKum/Source/Promise/ReadyStatus/ViewController/ReadyStatusViewController.swift
  KkuMulKum/Source/Promise/ViewModel/PromiseViewModel.swift
Labels: ✨ feat, 🛠️ fix, 💚 YouJin

#396 [fix] 최종 QA 반영
  KkuMulKum/Source/Home/View/TodayPromiseView.swift
Labels: 🛠️ fix, ❤️ SuYeon

#395 [Fix] 최종 QA 반영
  KkuMulKum.xcodeproj/project.pbxproj
  KkuMulKum/Resource/Info.plist
  KkuMulKum/Source/MyPage/ViewController/MyPageEditViewController.swift
  KkuMulKum/Source/MyPage/ViewController/MyPageViewController.swift
  KkuMulKum/Source/MyPage/ViewModel/MyPageEditViewModel.swift
Labels: ✨ feat, 🛠️ fix, 🧡 JiHoon
