Repository OMZigak/KKUYOS, pull requests merged in 2024-08, with the labels that each got.

#275 [fix] 프로필 등록하기 오류 해결
  KkuMulKum/Application/SceneDelegate.swift
  KkuMulKum/Network/Service/AuthService.swift
  KkuMulKum/Source/Onboarding/Login/ViewController/LoginViewController.swift
  KkuMulKum/Source/Onboarding/Profile/VIewController/ProfileSetupViewController.swift
  KkuMulKum/Source/Onboarding/Profile/ViewModel/ProfileSetupViewModel.swift
Labels: 🛠️ fix, 🧡 JiHoon

#274 [feat] 카카오 공유하기 + 비동기 함수 부분 리팩토링
  KkuMulKum.xcodeproj/project.pbxproj
  KkuMulKum/Network/Service/AuthService.swift
  KkuMulKum/Resource/Info.plist
  KkuMulKum/Source/MyPage/View/MyPageEtcSettingView.swift
  KkuMulKum/Source/MyPage/View/MyPageView.swift
  KkuMulKum/Source/MyPage/ViewController/MyPageViewController.swift
  KkuMulKum/Source/Onboarding/Login/VIewModel/LoginViewModel.swift
  KkuMulKum/Source/Onboarding/Login/ViewController/LoginViewController.swift
  KkuMulKum/Source/Onboarding/Profile/VIewController/ProfileSetupViewController.swift
  KkuMulKum/Source/Onboarding/Profile/ViewModel/ProfileSetupViewModel.swift
Labels: ✨ feat, ♻️ refactor

#283 [hotfix] AUthInter 오류수정
  KkuMulKum/Network/Service/AuthService.swift
Labels: 🛠️ fix, 🧡 JiHoon

#285 [feat] 마스터 엑세스토큰 주입
  KkuMulKum/Application/AppDelegate.swift
  KkuMulKum/Application/SceneDelegate.swift
  KkuMulKum/Source/Onboarding/Login/VIewModel/LoginViewModel.swift
  KkuMulKum/Source/Onboarding/Login/View/LoginView.swift
  KkuMulKum/Source/Onboarding/Login/ViewController/LoginViewController.swift
Labels: ✨ feat, 🛠️ fix, 🧡 JiHoon

#281 [fix] 프로필 이미지가 흐려지는 현상 수정 및 이미지 설정 코드 간결화
  KkuMulKum/Source/AddPromise/Cell/PlaceListCell.swift
  KkuMulKum/Source/AddPromise/Cell/SelectMemberCell.swift
  KkuMulKum/Source/MeetingInfo/Cell/MeetingMemberCell.swift
Labels: 🛠️ fix, ♻️ refactor, 💙 JinUng

#294 [refactor] 프로토콜 및 서비스타입 리팩
  KkuMulKum.xcodeproj/project.pbxproj
  KkuMulKum/Network/Service/AuthService.swift
  KkuMulKum/Source/Onboarding/ServiceProtocol/AuthServiceProtocol.swift
Labels: ✨ feat, 🧡 JiHoon

#299 [add] 라이브러리 추가
  KkuMulKum.xcodeproj/project.pbxproj
  KkuMulKum.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: 🧀 add, 💙 JinUng

#300 [refactor] 홈 및 내 모임 리스트 뷰 디자인 QA 반영
  KkuMulKum/Resource/Assets.xcassets/Image/img_board.imageset/Group 427320589.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_board.imageset/Group 427320589@2x.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_board.imageset/Group 427320589@3x.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_board_horizontal.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/Image/img_board_horizontal.imageset/img_board.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_board_horizontal.imageset/img_board@2x.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_board_horizontal.imageset/img_board@3x.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_board_vertical.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/Image/img_board_vertical.imageset/img_board_vertical.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_board_vertical.imageset/img_board_vertical@2x.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_board_vertical.imageset/img_board_vertical@3x.png
  KkuMulKum/Resource/Extension/NSAttributedString+.swift
  KkuMulKum/Resource/Extension/UIFont+.swift
  KkuMulKum/Source/Home/View/HomeView.swift
  KkuMulKum/Source/Home/View/TodayPromiseView.swift
  KkuMulKum/Source/Home/View/UpcomingPromiseCollecitonViewCell.swift
  KkuMulKum/Source/Home/ViewController/HomeViewController.swift
  KkuMulKum/Source/Home/ViewModel/HomeViewModel.swift
  KkuMulKum/Source/MeetingList/View/MeetingListView.swift
Labels: ♻️ refactor, ❤️ SuYeon

#302 [feat] 커스텀 액션 시트 구현하기
  KkuMulKum.xcodeproj/project.pbxproj
  KkuMulKum/Resource/Assets.xcassets/Image/img_delete_promise.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/Image/img_delete_promise.imageset/img_delete_promise.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_delete_promise.imageset/img_delete_promise@2x.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_delete_promise.imageset/img_delete_promise@3x.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_exit_meeting.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/Image/img_exit_meeting.imageset/img_exit_meeting.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_exit_meeting.imageset/img_exit_meeting@2x.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_exit_meeting.imageset/img_exit_meeting@3x.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_exit_promise.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/Image/img_exit_promise.imageset/img_exit_promise.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_exit_promise.imageset/img_exit_promise@2x.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_exit_promise.imageset/img_exit_promise@3x.png
  KkuMulKum/Resource/Component/CustomActionSheetController.swift
Labels: ✨ feat, 💙 JinUng

#304 [feat] 디자인 명세에 따른 약속 정보 뷰 수정
  KkuMulKum.xcodeproj/project.pbxproj
  KkuMulKum.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  KkuMulKum/Resource/Assets.xcassets/Icon/icon_delete_dark.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/Icon/icon_delete_dark.imageset/deleteDark.svg
  KkuMulKum/Resource/Assets.xcassets/Icon/icon_group_plus.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/Icon/icon_group_plus.imageset/ic_grpplus.svg
  KkuMulKum/Resource/Assets.xcassets/Icon/icon_plus_dark.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/Icon/icon_plus_dark.imageset/plusDark.svg
  KkuMulKum/Resource/Assets.xcassets/Image/img_empty_character.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/Image/img_empty_character.imageset/Frame 1171276907.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_empty_character.imageset/Frame 1171276907@2x.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_empty_character.imageset/Frame 1171276907@3x.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_level_01.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/Image/img_level_01.imageset/level01.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_level_01.imageset/level01@2x.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_level_01.imageset/level01@3x.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_level_02.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/Image/img_level_02.imageset/level02.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_level_02.imageset/level02@2x.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_level_02.imageset/level02@3x.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_level_03.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/Image/img_level_03.imageset/level03.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_level_03.imageset/level03@2x.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_level_03.imageset/level03@3x.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_level_04.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/Image/img_level_04.imageset/level04.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_level_04.imageset/level04@2x.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_level_04.imageset/level04@3x.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_meeting_info_banner.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/Image/img_meeting_info_banner.imageset/meetingInfoBanner.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_meeting_info_banner.imageset/meetingInfoBanner@2x.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_meeting_info_banner.imageset/meetingInfoBanner@3x.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_promise.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/Image/img_promise.imageset/receipt-subtract--shop-shopping-pay-payment-store-cash-bill-receipt-subtract-minus-remove.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_promise.imageset/receipt-subtract--shop-shopping-pay-payment-store-cash-bill-receipt-subtract-minus-remove@2x.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_promise.imageset/receipt-subtract--shop-shopping-pay-payment-store-cash-bill-receipt-subtract-minus-remove@3x.png
  KkuMulKum/Resource/Base/BaseViewController.swift
  KkuMulKum/Source/MeetingList/View/MeetingListView.swift
  KkuMulKum/Source/Promise/PagePromise/ViewController/PromiseViewController.swift
  KkuMulKum/Source/Promise/PromiseInfo/Cell/ParticipantCollectionViewCell.swift
  KkuMulKum/Source/Promise/PromiseInfo/View/PromiseInfoView.swift
  KkuMulKum/Source/Promise/PromiseInfo/ViewController/PromiseInfoViewController.swift
Labels: ✨ feat, 🛠️ fix, 🧀 add, 💚 YouJin

#307 [refactor] 네비게이션 바 경계선 구현 방식 변경
  KkuMulKum.xcodeproj/project.pbxproj
  KkuMulKum/Application/SceneDelegate.swift
  KkuMulKum/Resource/Base/BaseViewController.swift
  KkuMulKum/Resource/Extension/UINavigationController+.swift
  KkuMulKum/Source/Onboarding/Login/ViewController/LoginViewController.swift
  KkuMulKum/Source/Onboarding/Welcome/ViewController/WelcomeViewController.swift
Labels: ♻️ refactor, 💙 JinUng

#309 [refactor] ObservablePattern 코드 개선
  KkuMulKum/Resource/ObservablePattern/ObservablePattern.swift
Labels: ♻️ refactor, 💙 JinUng

#311 [refactor] 커스텀 액션 시트 액션 버튼 분기 처리
  KkuMulKum/Resource/Component/CustomActionSheetController.swift
Labels: ♻️ refactor, 💙 JinUng

#314 [refactor] CALayer를 이용한 네비게이션 바 경계선 설정 구현
  KkuMulKum/Resource/Extension/UINavigationController+.swift
Labels: ♻️ refactor, 💙 JinUng

#315 [feat] 약속 나가기, 삭제하기 플로우 구현
  KkuMulKum.xcodeproj/project.pbxproj
  KkuMulKum/Network/DTO/Model/Promises/MeetingPromisesModel.swift
  KkuMulKum/Resource/Assets.xcassets/Image/img_more.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/Image/img_more.imageset/img_more.svg
  KkuMulKum/Resource/Component/BottomSheet.swift
  KkuMulKum/Source/MeetingInfo/Cell/MeetingPromiseCell.swift
  KkuMulKum/Source/MeetingInfo/Service/MeetingInfoService.swift
  KkuMulKum/Source/MeetingInfo/ViewController/MeetingInfoViewController.swift
  KkuMulKum/Source/Promise/PagePromise/ViewController/PromiseViewController.swift
  KkuMulKum/Source/Promise/PagePromise/ViewController/RemovePromiseViewController.swift
Labels: ✨ feat, 🛠️ fix, 💚 YouJin

#318 [hotfix] auth_code 발금
  KkuMulKum/Application/SceneDelegate.swift
  KkuMulKum/Source/Onboarding/Login/VIewModel/LoginViewModel.swift
  KkuMulKum/Source/Onboarding/Login/ViewController/LoginViewController.swift
Labels: 🛠️ fix, 🧡 JiHoon

#320 [feat] 마이페이지 View 구현
  KkuMulKum.xcodeproj/project.pbxproj
  KkuMulKum/Resource/Assets.xcassets/Image/img_edit.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/Image/img_edit.imageset/edit.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_edit.imageset/img_edit 1.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_edit.imageset/img_edit 2.png
  KkuMulKum/Resource/Assets.xcassets/Image/img_edit.imageset/img_edit.png
  KkuMulKum/Source/MyPage/View/MyPageAlarmSettingView.swift
  KkuMulKum/Source/MyPage/View/MyPageContentView.swift
  KkuMulKum/Source/MyPage/View/MyPageEtcSettingView.swift
  KkuMulKum/Source/MyPage/View/MyPageView.swift
  KkuMulKum/Source/MyPage/ViewController/MyPageEditViewController.swift
  KkuMulKum/Source/MyPage/ViewController/MyPageViewController.swift
  KkuMulKum/Source/MyPage/ViewModel/MyPageViewModel.swift
Labels: ✨ feat, 🧡 JiHoon

#317 [feat] 약속 추가 플로우 변경된 기능 명세 반영하기
  KkuMulKum/Source/AddPromise/View/AddPromiseCompleteView.swift
  KkuMulKum/Source/AddPromise/View/AddPromiseView.swift
  KkuMulKum/Source/AddPromise/View/SelectMemberView.swift
  KkuMulKum/Source/AddPromise/View/SelectPenaltyView.swift
  KkuMulKum/Source/AddPromise/ViewController/SelectMemberViewController.swift
  KkuMulKum/Source/AddPromise/ViewModel/AddPromiseViewModel.swift
  KkuMulKum/Source/AddPromise/ViewModel/SelectMemberViewModel.swift
  KkuMulKum/Source/MeetingInfo/ViewController/MeetingInfoViewController.swift
  KkuMulKum/Source/MeetingInfo/ViewModel/MeetingInfoViewModel.swift
Labels: ✨ feat, 💙 JinUng

#323 [feat] 웹뷰 로딩하기
  KkuMulKum.xcodeproj/project.pbxproj
  KkuMulKum/Source/MyPage/View/MyPageEditView.swift
  KkuMulKum/Source/MyPage/ViewController/MyPageAskViewController.swift
  KkuMulKum/Source/MyPage/ViewController/MyPageEditViewController.swift
  KkuMulKum/Source/MyPage/ViewController/MyPageTermsViewController.swift
  KkuMulKum/Source/MyPage/ViewController/MyPageViewController.swift
  KkuMulKum/Source/MyPage/ViewModel/MyPageEditViewModel.swift
Labels: ✨ feat, 🧡 JiHoon

#325 [Feat] 마이페이지 API 연결
  KkuMulKum.xcodeproj/project.pbxproj
  KkuMulKum/Network/Service/AuthService.swift
  KkuMulKum/Network/Service/UserService.swift
  KkuMulKum/Network/TargetType/MypageTargetType.swift
  KkuMulKum/Source/Core/Auth/AuthInterceptor.swift
  KkuMulKum/Source/MyPage/MyPageServiceProtocol/MyPageUserServiceType.swift
  KkuMulKum/Source/MyPage/ViewController/MyPageViewController.swift
  KkuMulKum/Source/MyPage/ViewModel/MyPageEditViewModel.swift
  KkuMulKum/Source/MyPage/ViewModel/MyPageViewModel.swift
  KkuMulKum/Source/Onboarding/Login/VIewModel/LoginViewModel.swift
  KkuMulKum/Source/Onboarding/Nickname/ViewModel/NicknameViewModel.swift
  KkuMulKum/Source/Onboarding/Profile/ViewModel/ProfileSetupViewModel.swift
  KkuMulKum/Source/Onboarding/ServiceProtocol/AuthServiceProtocol.swift
Labels: ✨ feat, 🧡 JiHoon

#328 [fix] 모임 추가 플로우 QA 반영
  KkuMulKum/Source/AddMeeting/CheckInviteCode/View/CheckInviteCodeView.swift
  KkuMulKum/Source/AddMeeting/CheckInviteCode/View/JoinButtonView.swift
Labels: 🛠️ fix, ❤️ SuYeon

#329 [feat] 모임 상세 화면 삭제(나가기) 기능 및 바뀐 API 명세 반영하기
  KkuMulKum.xcodeproj/project.pbxproj
  KkuMulKum/Network/Service/MeetingService.swift
  KkuMulKum/Network/TargetType/MeetingTargetType.swift
  KkuMulKum/Source/MeetingInfo/Cell/MeetingPromiseCell.swift
  KkuMulKum/Source/MeetingInfo/Model/MeetingInfoPromiseModel.swift
  KkuMulKum/Source/MeetingInfo/Service/MeetingInfoService.swift
  KkuMulKum/Source/MeetingInfo/ViewController/MeetingInfoMoreViewController.swift
  KkuMulKum/Source/MeetingInfo/ViewController/MeetingInfoViewController.swift
  KkuMulKum/Source/MeetingInfo/ViewModel/MeetingInfoViewModel.swift
Labels: ✨ feat, 💙 JinUng

#331 [refactor] 준비 현황 뷰 디자인 명세 반영
  KkuMulKum.xcodeproj/project.pbxproj
  KkuMulKum/Source/Promise/ReadyStatus/Cell/OurReadyStatusCollectionViewCell.swift
  KkuMulKum/Source/Promise/ReadyStatus/View/ReadyStatusView.swift
Labels: ♻️ refactor, 💚 YouJin

#335 [refactor] 홈 화면 기능 QA 및 수정된 서버 명세 반영
  KkuMulKum.xcodeproj/project.pbxproj
  KkuMulKum/Network/DTO/Model/Promises/NearestPromiseResponseModel.swift
  KkuMulKum/Network/DTO/Model/Promises/UpcomingPromiseListResponseModel.swift
  KkuMulKum/Network/Service/HomeService.swift
  KkuMulKum/Source/Home/ServiceProtocol/HomeServiceProtocol.swift
  KkuMulKum/Source/Home/ServiceType/HomeServiceType.swift
  KkuMulKum/Source/Home/View/HomeView.swift
  KkuMulKum/Source/Home/View/TodayPromiseView.swift
  KkuMulKum/Source/Home/View/UpcomingPromiseCollecitonViewCell.swift
  KkuMulKum/Source/Home/ViewController/HomeViewController.swift
  KkuMulKum/Source/Home/ViewModel/HomeViewModel.swift
Labels: ♻️ refactor, ❤️ SuYeon

#339 [refactor] 내 모임 리스트 QA 반영
  KkuMulKum.xcodeproj/project.pbxproj
  KkuMulKum/Network/Service/MeetingListService.swift
  KkuMulKum/Network/Service/MeetingService.swift
  KkuMulKum/Network/TargetType/MeetingListTargetType.swift
  KkuMulKum/Source/Core/MainTabBarController.swift
  KkuMulKum/Source/MeetingList/ServiceProtocol/MeetingListServiceProtocol.swift
  KkuMulKum/Source/MeetingList/ServiceType/MeetingListServiceType.swift
  KkuMulKum/Source/MeetingList/View/MeetingListView.swift
  KkuMulKum/Source/MeetingList/View/MeetingTableViewCell.swift
  KkuMulKum/Source/MeetingList/ViewController/MeetingListViewController.swift
  KkuMulKum/Source/MeetingList/ViewModel/MeetingListViewModel.swift
Labels: ♻️ refactor, ❤️ SuYeon

#338 [feat] 약속 수정 플로우 구현
  KkuMulKum.xcodeproj/project.pbxproj
  KkuMulKum/Network/DTO/Model/Promises/EditPromiseRequestModel.swift
  KkuMulKum/Network/DTO/Model/Promises/ParticipateAvailabilityResponseModel.swift
  KkuMulKum/Network/Service/PromiseService.swift
  KkuMulKum/Network/TargetType/PromiseTargetType.swift
  KkuMulKum/Source/AddMeeting/CreateMeeting/ViewModel/CreateMeetingViewModel.swift
  KkuMulKum/Source/AddPromise/View/AddPromiseCompleteView.swift
  KkuMulKum/Source/AddPromise/View/AddPromiseView.swift
  KkuMulKum/Source/AddPromise/View/SelectMemberView.swift
  KkuMulKum/Source/AddPromise/View/SelectPenaltyView.swift
  KkuMulKum/Source/AddPromise/ViewController/AddPromiseCompleteViewController.swift
  KkuMulKum/Source/AddPromise/ViewController/AddPromiseViewController.swift
  KkuMulKum/Source/EditPromise/ServiceProtocol/EditPromiseServiceProtocol.swift
  KkuMulKum/Source/EditPromise/ViewController/ChooseContentViewController.swift
  KkuMulKum/Source/EditPromise/ViewController/ChooseMemberViewController.swift
  KkuMulKum/Source/EditPromise/ViewController/EditPromiseViewController.swift
  KkuMulKum/Source/EditPromise/ViewModel/EditPromiseViewModel.swift
  KkuMulKum/Source/Promise/PromiseInfo/View/PromiseInfoView.swift
  KkuMulKum/Source/Promise/PromiseInfo/ViewController/PromiseInfoViewController.swift
Labels: ✨ feat, 💚 YouJin

#330 [feat] 회원탈퇴/로그아웃 구현
  KkuMulKum.xcodeproj/project.pbxproj
  KkuMulKum/Application/SceneDelegate.swift
  KkuMulKum/Network/Service/UserService.swift
  KkuMulKum/Network/TargetType/MypageTargetType.swift
  KkuMulKum/Source/MyPage/MyPageServiceProtocol/MyPageUserServiceProtocol.swift
  KkuMulKum/Source/MyPage/ViewController/MyPageViewController.swift
  KkuMulKum/Source/MyPage/ViewModel/MyPageViewModel.swift
Labels: ✨ feat, 🧡 JiHoon

#342 [feat] 약속 관련 API 연결 및 명세 반영
  KkuMulKum.xcodeproj/project.pbxproj
  KkuMulKum/Network/DTO/Model/Promises/PromiseInfoResponseModel.swift
  KkuMulKum/Network/Service/PromiseService.swift
  KkuMulKum/Resource/Assets.xcassets/Image/img_promise_gray.imageset/Contents.json
  KkuMulKum/Resource/Assets.xcassets/Image/img_promise_gray.imageset/receipt-subtract--shop-shopping-pay-payment-store-cash-bill-receipt-subtract-minus-remove.svg
  KkuMulKum/Source/AddPromise/Cell/SelectMemberCell.swift
  KkuMulKum/Source/Promise/EditPromise/ServiceProtocol/EditPromiseServiceProtocol.swift
  KkuMulKum/Source/Promise/EditPromise/ViewController/ChooseContentViewController.swift
  KkuMulKum/Source/Promise/EditPromise/ViewController/ChooseMemberViewController.swift
  KkuMulKum/Source/Promise/EditPromise/ViewController/EditPromiseViewController.swift
  KkuMulKum/Source/Promise/EditPromise/ViewModel/EditPromiseViewModel.swift
  KkuMulKum/Source/Promise/PagePromise/ViewController/PromiseViewController.swift
  KkuMulKum/Source/Promise/PromiseInfo/ViewController/PromiseInfoViewController.swift
  KkuMulKum/Source/Promise/ReadyStatus/Cell/OurReadyStatusCollectionViewCell.swift
  KkuMulKum/Source/Promise/ServiceProtocol/PromiseServiceProtocol.swift
  KkuMulKum/Source/Promise/Tardy/View/TardyPenaltyView.swift
  KkuMulKum/Source/Promise/ViewModel/PromiseViewModel.swift
Labels: ✨ feat, 🛠️ fix, ♻️ refactor, 💚 YouJin

#343 [feat] 모임 상세 화면 약속 분기 처리
  KkuMulKum.xcodeproj/project.pbxproj
  KkuMulKum/Network/Service/MeetingService.swift
  KkuMulKum/Network/TargetType/MeetingTargetType.swift
  KkuMulKum/Source/MeetingInfo/Cell/MeetingPromiseCell.swift
  KkuMulKum/Source/MeetingInfo/Service/MeetingInfoService.swift
  KkuMulKum/Source/MeetingInfo/View/MeetingInfoView.swift
  KkuMulKum/Source/MeetingInfo/View/UnderlineSegmentedControl.swift
  KkuMulKum/Source/MeetingInfo/ViewController/MeetingInfoViewController.swift
  KkuMulKum/Source/MeetingInfo/ViewModel/MeetingInfoViewModel.swift
Labels: ✨ feat, 💙 JinUng

#341 [feat] 프로필 이미지 등록 API 구현
  KkuMulKum/Network/TargetType/Auth/AuthTargetType.swift
  KkuMulKum/Source/MyPage/View/MyPageContentView.swift
  KkuMulKum/Source/MyPage/View/MyPageEditView.swift
  KkuMulKum/Source/MyPage/View/MyPageView.swift
  KkuMulKum/Source/MyPage/ViewController/MyPageEditViewController.swift
  KkuMulKum/Source/MyPage/ViewController/MyPageViewController.swift
  KkuMulKum/Source/MyPage/ViewModel/MyPageEditViewModel.swift
Labels: ✨ feat, 🧡 JiHoon

#347 [feat] 릴리즈 디버그 분기
  KkuMulKum.xcodeproj/project.pbxproj
  KkuMulKum.xcodeproj/xcshareddata/xcschemes/KkuMulKum.xcscheme
  KkuMulKum/Network/TargetType/Auth/AuthTargetType.swift
  KkuMulKum/Network/TargetType/HomeTargetType.swift
  KkuMulKum/Network/TargetType/MeetingListTargetType.swift
  KkuMulKum/Network/TargetType/MeetingTargetType.swift
  KkuMulKum/Network/TargetType/MypageTargetType.swift
  KkuMulKum/Network/TargetType/PromiseTargetType.swift
  KkuMulKum/Network/TargetType/UtilTargetType.swift
  KkuMulKum/Resource/Bundle/Bundle.swift
Labels: ✨ feat, 🧡 JiHoon

#348 [refactor] 내가 속한 약속 분기 처리 및 자잘한 오류 수정
  KkuMulKum/Source/AddPromise/ViewController/AddPromiseCompleteViewController.swift
  KkuMulKum/Source/Promise/EditPromise/ViewController/ChooseContentViewController.swift
  KkuMulKum/Source/Promise/EditPromise/ViewController/ChooseMemberViewController.swift
  KkuMulKum/Source/Promise/EditPromise/ViewModel/EditPromiseViewModel.swift
  KkuMulKum/Source/Promise/PagePromise/ViewController/PromiseViewController.swift
  KkuMulKum/Source/Promise/PromiseInfo/ViewController/PromiseInfoViewController.swift
  KkuMulKum/Source/Promise/Tardy/ViewController/TardyViewController.swift
  KkuMulKum/Source/Promise/ViewModel/PromiseViewModel.swift
Labels: 🛠️ fix, ♻️ refactor, 💚 YouJin
